<?php
declare(strict_types=1);

return [
    [
        'key' => 'cant_create_gl_entry',
        'title' => "I Can't Create a New GL Entry",
        'classification' => 'WORKFLOW',
        'module' => 'Accounting',
        'module_key' => 'finance',
        'action' => 'create_gl_entry',
        'summary' => 'General Ledger entries are created from Accounting > General Ledger, not from a generic finance activity view.',
        'phrases' => [ "i can't create a new gl entry", 'cant create gl entry', 'cannot create general ledger entry', 'new gl entry missing', 'create journal entry', 'add journal entry', 'how do i create a gl entry', 'how can i create a gl entry', 'how do i create a general ledger entry', 'how do i create a journal entry' ],
        'search_terms' => [ 'cannot create general ledger entry', 'new GL entry missing', 'add journal entry', 'create journal entry', 'debit credit entry', 'accounting entry', 'permission denied GL', 'period closed', 'new entry button missing', 'save GL entry failed', 'how do i create a gl entry', 'how can i create a gl entry', 'how do i create a general ledger entry' ],
        'steps' => [ 'Open Accounting.', 'Select General Ledger.', 'Click New GL Entry.', 'Choose the entry date.', 'Add debit and credit lines.', 'Confirm total debits equal total credits.', 'Add memo and reference details.', 'Select Save Draft or Submit for Approval.', 'Approve the Secure Enclave confirmation if prompted.' ],
        'checks' => [ 'You must have permission to create GL entries.', 'Accounting must be enabled.', 'The accounting period must be open.', 'Required fields cannot be blank.', 'Debits and credits must balance before posting.' ],
        'admin_escalation' => [ 'You do not see Accounting.', 'You do not see General Ledger.', 'The New GL Entry button is missing.', 'You receive Permission Denied.', 'The accounting period is locked.' ],
        'related_articles' => [ 'Finance Overview', 'Creating a GL Entry', 'Understanding Debits and Credits', 'Permission Denied Messages', 'Secure Enclave Approvals' ],
        'permissions' => [ 'finance.edit' ],
        'feature_flags' => [ 'finance_v2_enabled' ],
    ],
    [
        'key' => 'cant_save_gl_entry',
        'title' => "I Can't Save a GL Entry",
        'classification' => 'VALIDATION',
        'module' => 'Accounting',
        'module_key' => 'finance',
        'action' => 'save_gl_entry',
        'summary' => 'GL save failures usually come from missing required fields, an invalid posting date, or line totals that do not balance.',
        'phrases' => [ "i can't save a gl entry", 'cant save gl entry', 'save gl entry failed', 'journal entry will not save' ],
        'search_terms' => [ 'save GL entry failed', 'journal entry will not save', 'cannot save accounting entry', 'required fields missing GL', 'GL validation error' ],
        'steps' => [ 'Review the posting date.', 'Confirm the entry has at least one debit line and one credit line.', 'Make sure totals balance exactly.', 'Fill in memo, account, and amount fields.', 'Save Draft again.', 'Submit for approval only after the draft saves cleanly.' ],
        'checks' => [ 'Required fields must be completed.', 'Dates must fall inside an open accounting period.', 'Debit and credit totals must match.', 'The record cannot be archived or already posted.', 'Any save warning in the form should be corrected before retrying.' ],
        'admin_escalation' => [ 'You see a permission error.', 'The save button is disabled even after the form is complete.', 'Every balanced draft still fails with the same error.' ],
        'related_articles' => [ 'Creating a GL Entry', 'The Accounting Period Is Closed', 'Permission Denied Messages' ],
        'permissions' => [ 'finance.edit' ],
        'feature_flags' => [ 'finance_v2_enabled' ],
    ],
    [
        'key' => 'cant_post_gl_entry',
        'title' => "I Can't Post a GL Entry",
        'classification' => 'LOCKED_STATE',
        'module' => 'Accounting',
        'module_key' => 'finance',
        'action' => 'post_gl_entry',
        'summary' => 'Posting is blocked when the entry is incomplete, unapproved, already posted, or tied to a closed period.',
        'phrases' => [ "i can't post a gl entry", 'cant post gl entry', 'post journal entry failed', 'cannot post accounting entry' ],
        'search_terms' => [ 'cannot post GL entry', 'post journal entry failed', 'GL post blocked', 'entry already posted', 'unapproved journal entry' ],
        'steps' => [ 'Open the draft entry.', 'Confirm the entry saved successfully.', 'Check whether approval is required.', 'Review the posting date and accounting period.', 'Submit or approve the entry if your workflow requires it.', 'Post the entry after all blocking warnings are cleared.' ],
        'checks' => [ 'The entry cannot already be posted.', 'Approval workflows must be completed first.', 'The accounting period must still be open.', 'Balanced totals are required.', 'Posting permissions must be available to your role.' ],
        'admin_escalation' => [ 'You do not have posting rights.', 'The period is closed and you cannot reopen it.', 'The system reports the record is locked or finalized.' ],
        'related_articles' => [ 'I Can\'t Save a GL Entry', 'The Accounting Period Is Closed', 'Secure Enclave Approvals' ],
        'permissions' => [ 'finance.edit' ],
        'feature_flags' => [ 'finance_v2_enabled' ],
    ],
    [
        'key' => 'gl_entry_not_balanced',
        'title' => 'My GL Entry Does Not Balance',
        'classification' => 'VALIDATION',
        'module' => 'Accounting',
        'module_key' => 'finance',
        'action' => 'balance_gl_entry',
        'summary' => 'A GL entry can only save or post when debit and credit totals are exactly equal.',
        'phrases' => [ 'my gl entry does not balance', 'gl entry not balanced', 'debits and credits do not match', 'journal entry out of balance' ],
        'search_terms' => [ 'GL entry does not balance', 'debits and credits do not match', 'journal entry out of balance', 'accounting totals mismatch' ],
        'steps' => [ 'Review every debit line.', 'Review every credit line.', 'Check for blank or duplicated amounts.', 'Correct any rounding or transposed values.', 'Recalculate the totals.', 'Save the draft again once both sides match.' ],
        'checks' => [ 'Debit total must equal credit total.', 'Each line needs the correct account and amount.', 'Do not leave partial lines in the entry.', 'Zero-value lines should be removed unless intentionally required.' ],
        'admin_escalation' => [ 'A balanced entry still shows as out of balance.', 'The system recalculation appears incorrect across multiple entries.' ],
        'related_articles' => [ 'I Can\'t Save a GL Entry', 'Creating a GL Entry', 'Understanding Debits and Credits' ],
        'permissions' => [ 'finance.edit' ],
        'feature_flags' => [ 'finance_v2_enabled' ],
    ],
    [
        'key' => 'accounting_period_closed',
        'title' => 'The Accounting Period Is Closed',
        'classification' => 'LOCKED_STATE',
        'module' => 'Accounting',
        'module_key' => 'finance',
        'action' => 'manage_accounting_period',
        'summary' => 'Closed periods block new entries, edits, and posting so prior reporting stays consistent.',
        'phrases' => [ 'the accounting period is closed', 'period closed', 'cannot post because period is locked', 'gl entry period locked' ],
        'search_terms' => [ 'accounting period is closed', 'period locked', 'cannot post because period is locked', 'general ledger closed month' ],
        'steps' => [ 'Confirm the entry date.', 'Switch to an open period if the transaction belongs there.', 'Save the entry as a draft if your process allows later posting.', 'Contact the accounting administrator if the closed period must be reopened.' ],
        'checks' => [ 'Closed periods block create, edit, and post actions.', 'Only authorized roles should reopen periods.', 'Reports may depend on the period staying locked.' ],
        'admin_escalation' => [ 'The transaction must be recorded in the closed period.', 'You need a period reopened.', 'You do not have authority to unlock the period.' ],
        'related_articles' => [ 'I Can\'t Post a GL Entry', 'I Can\'t Create a New GL Entry' ],
        'permissions' => [ 'finance.edit' ],
        'proposed_actions' => [
            [ 'command' => 'verify_integrity', 'title' => 'Run Integrity Check', 'summary' => 'Verify the finance state before reopening a locked period.', 'risk_level' => 'low', 'requires_approval' => false ],
        ],
    ],
    [
        'key' => 'cant_see_accounting_module',
        'title' => "I Can't See the Accounting Module",
        'classification' => 'PERMISSION',
        'module' => 'Accounting',
        'module_key' => 'finance',
        'action' => 'view_accounting_module',
        'summary' => 'A missing Accounting module usually means the current role does not include access or the module is not enabled for the workspace.',
        'phrases' => [ "i can't see the accounting module", 'cant see accounting module', 'accounting module missing', 'finance module missing' ],
        'search_terms' => [ 'accounting module missing', 'finance module missing', 'cannot see accounting', 'general ledger menu missing' ],
        'steps' => [ 'Refresh the page and return to the main navigation.', 'Look for Accounting or Finance in the navigation.', 'Confirm you are signed in with the expected account.', 'If the module is still missing, request a permission review.' ],
        'checks' => [ 'The module may be hidden by role permissions.', 'The module may be disabled in the workspace.', 'A stale session can hide recent access changes until refresh.' ],
        'admin_escalation' => [ 'The module stays hidden after refresh.', 'Your role should include accounting access.', 'Other users can see Accounting but you cannot.' ],
        'related_articles' => [ 'Understanding Permissions', 'Why Some Pages or Buttons Are Hidden', 'Permission Denied Messages' ],
        'permissions' => [ 'finance.view' ],
        'proposed_actions' => [
            [ 'command' => 'audit_permissions', 'title' => 'Audit Permissions', 'summary' => 'Review the current permission set for access to Accounting.', 'risk_level' => 'low', 'requires_approval' => false ],
        ],
    ],
    [
        'key' => 'cant_see_new_entry_button',
        'title' => "I Can't See the New Entry Button",
        'classification' => 'PERMISSION',
        'module' => 'Accounting',
        'module_key' => 'finance',
        'action' => 'show_new_entry_button',
        'summary' => 'Missing create buttons usually point to create permission, the wrong page, or a locked workflow state.',
        'phrases' => [ "i can't see the new entry button", 'new entry button missing', 'cannot see create button', 'missing add button' ],
        'search_terms' => [ 'new entry button missing', 'missing add button', 'cannot see create button', 'new GL entry button missing' ],
        'steps' => [ 'Open the exact list or ledger screen where new entries are created.', 'Check whether the record list is read-only, archived, or finalized.', 'Refresh the page after any recent role change.', 'If the button never appears, request a permission review.' ],
        'checks' => [ 'Create permission may be missing.', 'You might be on a view-only screen.', 'The workflow may be locked for the current period or batch.' ],
        'admin_escalation' => [ 'The create button should be available for your role.', 'The page is stuck in read-only mode for all users.' ],
        'related_articles' => [ 'Why Some Pages or Buttons Are Hidden', 'I Can\'t Create a New GL Entry' ],
        'permissions' => [ 'finance.edit' ],
    ],
    [
        'key' => 'cant_create_donation',
        'title' => "I Can't Create a Donation",
        'classification' => 'WORKFLOW',
        'module' => 'Donations',
        'module_key' => 'donations',
        'action' => 'create_donation',
        'summary' => 'Donation creation belongs in the Donations workflow and can be blocked by access, batch state, or missing donor details.',
        'phrases' => [ "i can't create a donation", 'cant create donation', 'new donation missing', 'cannot add donation', 'how do i create a new donation', 'how can i create a donation', 'where do i create a donation' ],
        'search_terms' => [ 'cannot create donation', 'new donation missing', 'add donation', 'donation create blocked', 'donation button missing', 'how do i create a new donation', 'how can i create a donation' ],
        'steps' => [ 'Open Donations.', 'Start a new gift or donation record from the correct batch or entry screen.', 'Choose the donor.', 'Enter date, amount, fund, and payment details.', 'Save the record and confirm any approval step if prompted.' ],
        'checks' => [ 'You need donation create access.', 'The batch or period cannot be locked.', 'Required donor and payment fields must be complete.' ],
        'admin_escalation' => [ 'You do not see the donation create action.', 'The batch is locked and must be reopened.', 'Permission Denied appears when saving.' ],
        'related_articles' => [ 'Donations Overview', 'I Can\'t Edit a Donation', 'Permission Denied Messages' ],
        'permissions' => [ 'donations.edit' ],
    ],
    [
        'key' => 'cant_edit_donation',
        'title' => "I Can't Edit a Donation",
        'classification' => 'LOCKED_STATE',
        'module' => 'Donations',
        'module_key' => 'donations',
        'action' => 'edit_donation',
        'summary' => 'Donation edits can be blocked by finalized batches, permissions, or records that already moved to a locked reconciliation state.',
        'phrases' => [ "i can't edit a donation", 'cant edit donation', 'donation locked', 'cannot change donation' ],
        'search_terms' => [ 'cannot edit donation', 'donation locked', 'change donation blocked', 'finalized donation record' ],
        'steps' => [ 'Open the donation record.', 'Check whether the batch is open.', 'Confirm the gift has not already been finalized or deposited.', 'Make the needed change and save if the record is editable.', 'If locked, ask the batch owner or administrator for the next step.' ],
        'checks' => [ 'Finalized or deposited gifts may be locked.', 'Edit permission may be missing.', 'The current batch may be closed.' ],
        'admin_escalation' => [ 'The gift must be changed after deposit or finalization.', 'You cannot reopen the batch yourself.' ],
        'related_articles' => [ 'I Can\'t Create a Donation', 'I Can\'t Create a Deposit Batch' ],
        'permissions' => [ 'donations.edit' ],
    ],
    [
        'key' => 'cant_see_new_donation_button',
        'title' => "I Don't See the New Donation Button",
        'classification' => 'PERMISSION',
        'module' => 'Donations',
        'module_key' => 'donations',
        'action' => 'create_donation',
        'summary' => 'A missing donation create button usually means the current role is view-only, the batch screen is locked, or the user is on the wrong page.',
        'phrases' => [ "i don't see the new donation button", 'new donation button missing', 'cant see donation button', 'cannot see add donation button' ],
        'search_terms' => [ 'new donation button missing', 'cannot see add donation button', 'donation create button missing', 'permission denied donation create' ],
        'steps' => [ 'Open the Donations module.', 'Go to the main donation list or batch entry screen.', 'Confirm you are not on a read-only detail page.', 'Refresh after any recent role change.', 'If the create button still does not appear, request a permission review.' ],
        'checks' => [ 'Donation create permission may be missing.', 'You may be on a finalized or read-only batch.', 'The button can remain hidden until a stale session is refreshed.' ],
        'admin_escalation' => [ 'Other donation users can see the button but you cannot.', 'The donations screen stays read-only after refresh.', 'You receive Permission Denied when opening the create flow.' ],
        'related_articles' => [ 'I Can\'t Create a Donation', 'Why Some Pages or Buttons Are Hidden', 'Permission Denied Messages' ],
        'permissions' => [ 'donations.edit' ],
    ],
    [
        'key' => 'cant_create_deposit_batch',
        'title' => "I Can't Create a Deposit Batch",
        'classification' => 'WORKFLOW',
        'module' => 'Donations',
        'module_key' => 'donations',
        'action' => 'create_deposit_batch',
        'summary' => 'Deposit batches require the right donations workflow, an open period, and access to create and balance batch records.',
        'phrases' => [ "i can't create a deposit batch", 'cant create deposit batch', 'new deposit batch missing', 'cannot start batch' ],
        'search_terms' => [ 'cannot create deposit batch', 'new deposit batch missing', 'start donation batch', 'create bank batch' ],
        'steps' => [ 'Open Donations.', 'Go to the deposit batch screen.', 'Create a new batch for the correct date.', 'Add the related gift records.', 'Balance the batch before finalizing.' ],
        'checks' => [ 'Create permission must be available.', 'The donation period must be open.', 'The batch cannot duplicate an existing finalized batch for the same deposit.' ],
        'admin_escalation' => [ 'The batch create action is missing.', 'The batch flow is locked by policy or period.' ],
        'related_articles' => [ 'My Deposit Batch Does Not Balance', 'I Can\'t Create a Donation' ],
        'permissions' => [ 'donations.edit' ],
    ],
    [
        'key' => 'deposit_batch_not_balanced',
        'title' => 'My Deposit Batch Does Not Balance',
        'classification' => 'VALIDATION',
        'module' => 'Donations',
        'module_key' => 'donations',
        'action' => 'balance_deposit_batch',
        'summary' => 'A deposit batch must balance to its gift rows and total deposit amount before it can be finalized.',
        'phrases' => [ 'my deposit batch does not balance', 'deposit batch not balanced', 'batch totals do not match', 'cannot finalize deposit batch' ],
        'search_terms' => [ 'deposit batch does not balance', 'batch totals do not match', 'cannot finalize deposit batch', 'gift totals mismatch' ],
        'steps' => [ 'Review every gift row in the batch.', 'Check the total batch amount.', 'Correct any duplicated, missing, or mistyped gift amount.', 'Recalculate the batch total.', 'Finalize only after the displayed totals match.' ],
        'checks' => [ 'Gift rows must match the deposit total.', 'No draft or partial rows should remain.', 'Finalization should not happen until totals match exactly.' ],
        'admin_escalation' => [ 'Totals stay inconsistent after review.', 'The recalculation appears incorrect for multiple batches.' ],
        'related_articles' => [ 'I Can\'t Create a Deposit Batch', 'I Can\'t Create a Donation' ],
        'permissions' => [ 'donations.edit' ],
    ],
    [
        'key' => 'cant_send_newsletter',
        'title' => "I Can't Send a Newsletter",
        'classification' => 'CONFIGURATION',
        'module' => 'Newsletter',
        'module_key' => 'newsletter',
        'action' => 'send_newsletter',
        'summary' => 'Newsletter sending depends on sender configuration, audience selection, and queue delivery working normally.',
        'phrases' => [ "i can't send a newsletter", 'cant send newsletter', 'newsletter send blocked', 'cannot send campaign' ],
        'search_terms' => [ 'cannot send newsletter', 'newsletter send blocked', 'campaign send failed', 'email provider misconfigured newsletter' ],
        'steps' => [ 'Open Newsletter.', 'Confirm the campaign content and subject are complete.', 'Review sender profile and audience selection.', 'Run a test send if available.', 'Send the campaign only after the test succeeds.' ],
        'checks' => [ 'Sender configuration must be complete.', 'The audience cannot be empty.', 'Queue workers and email delivery must be healthy.', 'Send permission must be available.' ],
        'admin_escalation' => [ 'The test send fails.', 'The provider or sender profile is misconfigured.', 'Queue jobs are failing repeatedly.' ],
        'related_articles' => [ 'I Can\'t Send a Test Email', 'Email Settings', 'Worker status loaded.' ],
        'permissions' => [ 'newsletter.edit' ],
        'proposed_actions' => [
            [ 'command' => 'check_workers', 'title' => 'Check Worker Status', 'summary' => 'Review queue worker health for newsletter delivery.', 'risk_level' => 'low', 'requires_approval' => false ],
        ],
    ],
    [
        'key' => 'cant_send_test_email',
        'title' => "I Can't Send a Test Email",
        'classification' => 'SYSTEM',
        'module' => 'Newsletter',
        'module_key' => 'newsletter',
        'action' => 'send_test_email',
        'summary' => 'Newsletter test sends usually fail because the sender profile, provider settings, or queue processing path is incomplete.',
        'phrases' => [ 'the newsletter test email wont send', "the newsletter test email won't send", "i can't send a test email", 'cant send test email' ],
        'search_terms' => [ 'newsletter test email won\'t send', 'cannot send test email', 'campaign test send failed', 'sender profile missing', 'failed queue job email' ],
        'steps' => [ 'Open the newsletter campaign.', 'Review the sender profile.', 'Confirm the test address is valid.', 'Send the test again from the current campaign screen.', 'Check for a delivery or queue warning after retrying.' ],
        'checks' => [ 'An email provider must be configured.', 'A sender profile or from-address must exist.', 'Queue workers must be active.', 'The current user must have newsletter send access.' ],
        'admin_escalation' => [ 'The same test send fails repeatedly.', 'No sender profile is configured.', 'Queue or provider diagnostics show errors.' ],
        'related_articles' => [ 'I Can\'t Send a Newsletter', 'Email Settings', 'Understanding Nonces' ],
        'permissions' => [ 'newsletter.edit' ],
        'proposed_actions' => [
            [ 'command' => 'check_workers', 'title' => 'Check Worker Status', 'summary' => 'Review queue worker health for newsletter test delivery.', 'risk_level' => 'low', 'requires_approval' => false ],
            [ 'command' => 'run_full_diagnostics', 'title' => 'Run Diagnostics', 'summary' => 'Collect delivery-related diagnostics before changing configuration.', 'risk_level' => 'low', 'requires_approval' => false ],
        ],
    ],
    [
        'key' => 'cant_publish_page',
        'title' => "I Can't Publish a Website Page",
        'classification' => 'PERMISSION',
        'module' => 'Website',
        'module_key' => 'website',
        'action' => 'publish_page',
        'summary' => 'Publishing is blocked when the user lacks publish rights, the page is incomplete, or the page is being edited from the wrong website workflow.',
        'phrases' => [ "i can't publish a website page", "i can't publish a page", 'cant publish page', 'publish page failed' ],
        'search_terms' => [ 'cannot publish page', 'publish website page failed', 'page publish blocked', 'website publish permission denied' ],
        'steps' => [ 'Open the page from the Website module.', 'Save the draft first.', 'Review required page fields and slug details.', 'Preview the page.', 'Publish from the page workflow once validation passes.', 'Approve the Secure Enclave confirmation if prompted.' ],
        'checks' => [ 'Publish permission must be available.', 'The page must save as a valid draft first.', 'Required title, slug, and content fields must be complete.' ],
        'admin_escalation' => [ 'The Publish action is missing.', 'Permission Denied appears on publish.', 'The page is stuck in a locked or unpublished state despite saving cleanly.' ],
        'related_articles' => [ 'Creating a Page', 'Editing a Page', 'Permission Denied Messages' ],
        'permissions' => [ 'website.edit' ],
    ],
    [
        'key' => 'cant_edit_page',
        'title' => "I Can't Edit a Website Page",
        'classification' => 'PERMISSION',
        'module' => 'Website',
        'module_key' => 'website',
        'action' => 'edit_page',
        'summary' => 'Website page editing can be blocked by missing edit rights, opening the wrong page view, or trying to edit a locked record.',
        'phrases' => [ "i can't edit a website page", "i can't edit a page", 'cant edit page', 'page is read only' ],
        'search_terms' => [ 'cannot edit website page', 'page is read only', 'edit page permission denied', 'website page locked' ],
        'steps' => [ 'Open Website.', 'Go to the Pages list.', 'Open the page in edit mode.', 'Confirm the page is not archived or locked.', 'Save the change from the page editor.' ],
        'checks' => [ 'Edit permission must be available.', 'The page cannot be archived or locked.', 'You must be in the page editor, not a preview-only view.' ],
        'admin_escalation' => [ 'The page always opens in read-only mode.', 'Edit controls are hidden for a user who should have access.' ],
        'related_articles' => [ 'Creating a Page', 'Why Some Pages or Buttons Are Hidden' ],
        'permissions' => [ 'website.edit' ],
    ],
    [
        'key' => 'cant_upload_file',
        'title' => "I Can't Upload a File",
        'classification' => 'VALIDATION',
        'module' => 'Drive & Files',
        'module_key' => 'drive',
        'action' => 'upload_file',
        'summary' => 'File uploads usually fail because of access, unsupported file type, file size, or folder context problems.',
        'phrases' => [ "i can't upload a file", 'cant upload file', 'upload failed', 'file upload blocked' ],
        'search_terms' => [ 'cannot upload file', 'file upload blocked', 'upload failed', 'unsupported file type', 'folder permission upload' ],
        'steps' => [ 'Open the correct Drive or file area.', 'Choose the target folder.', 'Confirm the file type and size are allowed.', 'Retry the upload from the current page.', 'Wait for the success toast before navigating away.' ],
        'checks' => [ 'Upload permission must be available.', 'The folder must allow uploads.', 'The file type and size must be accepted.', 'A stale page can cause upload security errors after long idle time.' ],
        'admin_escalation' => [ 'All file uploads fail in the same area.', 'The folder is missing or inaccessible.', 'The same valid file fails repeatedly.' ],
        'related_articles' => [ 'Managing File Uploads', 'Understanding Nonces', 'Permission Denied Messages' ],
        'permissions' => [ 'drive.edit' ],
    ],
    [
        'key' => 'cant_find_file',
        'title' => "I Can't Find a File",
        'classification' => 'WORKFLOW',
        'module' => 'Drive & Files',
        'module_key' => 'drive',
        'action' => 'find_file',
        'summary' => 'Missing files are often in a different folder, hidden by permissions, or outside the current search scope.',
        'phrases' => [ "i can't find a file", 'cant find file', 'file missing', 'search cannot find file' ],
        'search_terms' => [ 'cannot find file', 'file missing', 'drive search no file', 'document not visible' ],
        'steps' => [ 'Search by the file name only first.', 'Try the parent folder or related person record.', 'Check whether filters are hiding archived or older files.', 'Confirm you are looking in the correct workspace location.' ],
        'checks' => [ 'Permissions may hide folders or files.', 'Filters may exclude archived or older items.', 'The file may have been moved to another folder.' ],
        'admin_escalation' => [ 'The file should exist but is missing for multiple users.', 'Search fails even with the exact known file name.' ],
        'related_articles' => [ 'Searching Across Metis', 'Managing File Uploads' ],
        'permissions' => [ 'drive.view' ],
    ],
    [
        'key' => 'cant_create_calendar_event',
        'title' => "I Can't Create a Calendar Event",
        'classification' => 'PERMISSION',
        'module' => 'Calendar',
        'module_key' => 'calendar',
        'action' => 'create_calendar_event',
        'summary' => 'Calendar event creation can be blocked by calendar permissions, the wrong calendar selection, or required event fields.',
        'phrases' => [ "i can't create a calendar event", 'cant create calendar event', 'new calendar event missing', 'cannot add event' ],
        'search_terms' => [ 'cannot create calendar event', 'new calendar event missing', 'calendar create blocked', 'cannot add event' ],
        'steps' => [ 'Open Calendar.', 'Select the target calendar.', 'Choose New Event.', 'Enter title, date, and time.', 'Save the event and confirm the success message.' ],
        'checks' => [ 'Create permission must exist for the selected calendar.', 'Required event fields must be complete.', 'You must be on a calendar that allows event creation.' ],
        'admin_escalation' => [ 'The New Event button is missing.', 'The target calendar is visible but never editable.' ],
        'related_articles' => [ 'Creating a Calendar Event', 'Understanding Calendar Sharing' ],
        'permissions' => [ 'calendar.edit' ],
    ],
    [
        'key' => 'cant_create_user',
        'title' => "I Can't Create a New User",
        'classification' => 'WORKFLOW',
        'module' => 'People & Permissions',
        'module_key' => 'people',
        'action' => 'create_user',
        'summary' => 'New Metis users are added from People > People List. Role assignment, workspace access, and other access changes happen after the base person record is created.',
        'phrases' => [ "i can't create a new user", 'cant create new user', 'cannot create user', 'how do i create a new user', 'how can i create a new user', 'how do i add a user', 'how do i create a user' ],
        'search_terms' => [ 'cannot create user', 'create metis user', 'add user in people', 'people add person', 'new user missing people', 'how do i create a new user', 'how do i add a user', 'add person button missing' ],
        'steps' => [ 'Open People.', 'Go to People List.', 'Click Add Person.', 'Enter first name, last name, and email address.', 'Save the person record.', 'Open the new profile if you need to assign roles, workspace access, or other permissions.' ],
        'checks' => [ 'You need permission to create people records.', 'The email address should be valid and not already in use.', 'Workspace access is a follow-up step after the base person record is saved.', 'If Add Person is missing, verify you are on People List and not only the dashboard.' ],
        'admin_escalation' => [ 'The Add Person button is missing on People List.', 'The save fails with Permission Denied.', 'A valid person record still cannot be created after retrying.' ],
        'related_articles' => [ 'Understanding People Records', 'Assigning Roles', 'Permission Denied Messages' ],
        'permissions' => [ 'people.create' ],
    ],
    [
        'key' => 'cant_assign_role',
        'title' => "I Can't Assign a Role",
        'classification' => 'PERMISSION',
        'module' => 'People & Permissions',
        'module_key' => 'people',
        'action' => 'assign_role',
        'summary' => 'Role assignment is limited to users with access to manage permissions and can also be blocked when the target user or role is incomplete.',
        'phrases' => [ "i can't assign a role", 'cant assign role', 'cannot grant role', 'role assignment blocked', 'how do i assign a role', 'how can i assign a role', 'how do i give a user a role' ],
        'search_terms' => [ 'cannot assign role', 'grant role blocked', 'role assignment permission denied', 'cannot update user role', 'how do i assign a role', 'how do i give a user a role' ],
        'steps' => [ 'Open the user record.', 'Go to roles or permissions.', 'Choose the role to assign.', 'Save the record.', 'Confirm the updated access after refresh.' ],
        'checks' => [ 'You need permission to manage user roles.', 'The target role must exist.', 'The user record must be editable and active.' ],
        'admin_escalation' => [ 'The roles section is hidden.', 'The save fails with Permission Denied.', 'The role list is incomplete or empty.' ],
        'related_articles' => [ 'Assigning Roles', 'Understanding Permissions' ],
        'permissions' => [ 'people.edit' ],
    ],
    [
        'key' => 'cant_find_person_record',
        'title' => "I Can't Find a Person Record",
        'classification' => 'WORKFLOW',
        'module' => 'People & Permissions',
        'module_key' => 'people',
        'action' => 'find_person_record',
        'summary' => 'Missing person records are often caused by search wording, filters, duplicate assumptions, or visibility restrictions.',
        'phrases' => [ "i can't find a person record", 'cant find person record', 'cannot find person', 'person search missing result' ],
        'search_terms' => [ 'cannot find person record', 'person search missing result', 'staff member not in people', 'record not visible people' ],
        'steps' => [ 'Search by last name or email first.', 'Remove narrow filters.', 'Check for alternate display name spelling.', 'Review whether the person is archived or inactive.' ],
        'checks' => [ 'Search filters may be hiding inactive people.', 'Visibility may depend on role or workspace context.', 'The record may exist under a different display name or email.' ],
        'admin_escalation' => [ 'The person record is confirmed to exist but never appears for any valid search.' ],
        'related_articles' => [ 'Understanding People Records', 'Searching Across Metis' ],
        'permissions' => [ 'people.view' ],
    ],
    [
        'key' => 'cant_run_report',
        'title' => "I Can't Run a Report",
        'classification' => 'PERMISSION',
        'module' => 'Reports',
        'module_key' => 'reports',
        'action' => 'run_report',
        'summary' => 'Report execution can fail because the report is not available to your role, the required filters are incomplete, or the source module is unavailable.',
        'phrases' => [ "i can't run a report", 'cant run report', 'report will not run', 'report blocked' ],
        'search_terms' => [ 'cannot run report', 'report will not run', 'report blocked', 'report permission denied', 'report filter missing' ],
        'steps' => [ 'Open the target report.', 'Review required filters.', 'Run the report from the current screen.', 'Wait for the result or export option to load.', 'Adjust the filter range if the report rejects the current scope.' ],
        'checks' => [ 'Report access permission must exist.', 'Required filters must be complete.', 'The source module must be enabled and available.' ],
        'admin_escalation' => [ 'The report is missing for a role that should have it.', 'The report fails consistently even with valid filters.' ],
        'related_articles' => [ 'Running a Report', 'Filtering Reports', 'Understanding Report Permissions' ],
        'permissions' => [ 'reports.view' ],
    ],
    [
        'key' => 'cant_export_report',
        'title' => "I Can't Export a Report",
        'classification' => 'PERMISSION',
        'module' => 'Reports',
        'module_key' => 'reports',
        'action' => 'export_report',
        'summary' => 'Report export depends on both report visibility and export permission, and it may be blocked until the report runs successfully first.',
        'phrases' => [ "i can't export a report", 'cant export report', 'report export blocked', 'download report failed' ],
        'search_terms' => [ 'cannot export report', 'report export blocked', 'download report failed', 'export permission denied' ],
        'steps' => [ 'Run the report first.', 'Confirm the results loaded correctly.', 'Use the export option from the report view.', 'Wait for the file download to start before retrying.' ],
        'checks' => [ 'The report must run successfully before export.', 'Export permission may be separate from view permission.', 'Browser download blocking can interrupt the export flow.' ],
        'admin_escalation' => [ 'The export option is hidden for a role that should have it.', 'The export fails for multiple reports or users.' ],
        'related_articles' => [ 'Exporting Reports', 'Running a Report' ],
        'permissions' => [ 'reports.view' ],
    ],
    [
        'key' => 'cant_save_settings',
        'title' => "I Can't Save Settings",
        'classification' => 'PERMISSION',
        'module' => 'Settings',
        'module_key' => 'settings',
        'action' => 'save_settings',
        'summary' => 'Settings saves can fail because the current role lacks manage access, required values are invalid, or the page has an expired request token.',
        'phrases' => [ "i can't save settings", 'cant save settings', 'settings save failed', 'cannot update settings' ],
        'search_terms' => [ 'cannot save settings', 'settings save failed', 'invalid settings form', 'settings permission denied', 'expired nonce settings' ],
        'steps' => [ 'Review the settings form for missing or invalid values.', 'Refresh the page if it has been open for a long time.', 'Save the settings again from the current screen.', 'Check the returned message for the exact blocked field or permission.' ],
        'checks' => [ 'Settings manage permission must exist.', 'Required values must be valid.', 'A stale page can cause a nonce or CSRF failure.' ],
        'admin_escalation' => [ 'Every settings page fails to save.', 'The same valid change is rejected repeatedly.', 'You do not have permission to manage settings.' ],
        'related_articles' => [ 'Settings Overview', 'Understanding Nonces', 'Permission Denied Messages' ],
        'permissions' => [ 'settings.manage' ],
    ],
    [
        'key' => 'cant_access_module',
        'title' => "I Can't Access a Module",
        'classification' => 'PERMISSION',
        'module' => 'Metis',
        'module_key' => 'portal',
        'action' => 'access_module',
        'summary' => 'Module access failures usually come from role-based visibility or a module that is disabled for the workspace.',
        'phrases' => [ "i can't access a module", 'cant access module', 'module access denied', 'module missing from navigation' ],
        'search_terms' => [ 'cannot access module', 'module missing from navigation', 'module access denied', 'hidden module metis' ],
        'steps' => [ 'Refresh the page.', 'Check the main navigation.', 'Confirm you are using the correct account.', 'Open the module from the standard menu instead of an old bookmark.' ],
        'checks' => [ 'The role may not include module visibility.', 'The module may be disabled.', 'Direct bookmarks can fail when the route moved or access changed.' ],
        'admin_escalation' => [ 'The module should exist for your role but never appears.', 'You receive Permission Denied from a valid module link.' ],
        'related_articles' => [ 'Using the Left Navigation Menu', 'Why Some Pages or Buttons Are Hidden', 'Permission Denied Messages' ],
        'permissions' => [ 'view' ],
    ],
    [
        'key' => 'permission_denied',
        'title' => 'I See Permission Denied',
        'classification' => 'PERMISSION',
        'module' => 'Metis',
        'module_key' => 'portal',
        'action' => 'permission_denied',
        'summary' => 'Permission Denied means the current account can reach part of the workflow but is blocked from the requested action itself.',
        'phrases' => [ 'i see permission denied', 'permission denied', 'access denied', 'not authorized' ],
        'search_terms' => [ 'permission denied', 'access denied', 'not authorized', 'action blocked by permission' ],
        'steps' => [ 'Read the full message.', 'Confirm the page and action you attempted.', 'Retry only if you changed role, record, or page context.', 'Request a permission review if the action should be part of your job.' ],
        'checks' => [ 'The action may require create, edit, publish, export, or admin permission.', 'The page may be visible even when the action is blocked.', 'A different role or module path may be required.' ],
        'admin_escalation' => [ 'The denied action should be available for your role.', 'A recent role change has not taken effect.' ],
        'related_articles' => [ 'Permission Denied Messages', 'Understanding Permissions' ],
        'permissions' => [ 'view' ],
        'proposed_actions' => [
            [ 'command' => 'audit_permissions', 'title' => 'Audit Permissions', 'summary' => 'Review the current permission set for this workflow.', 'risk_level' => 'low', 'requires_approval' => false ],
        ],
    ],
    [
        'key' => 'button_does_nothing',
        'title' => 'A Button Does Nothing',
        'classification' => 'SYSTEM',
        'module' => 'Metis',
        'module_key' => 'portal',
        'action' => 'button_noop',
        'summary' => 'A button that appears inactive can indicate validation blocking, a stale page, or a request that failed before the result displayed.',
        'phrases' => [ 'a button does nothing', 'button does nothing', 'clicking button does nothing', 'action button no response' ],
        'search_terms' => [ 'button does nothing', 'clicking button no response', 'action button not working', 'stale page button' ],
        'steps' => [ 'Look for validation warnings on the page.', 'Refresh the page if it has been open for a while.', 'Retry the action once from the current page state.', 'Check whether a required field or selection is missing.' ],
        'checks' => [ 'Form validation may be blocking submission.', 'The page may be using an expired request token.', 'A background request may have failed silently.' ],
        'admin_escalation' => [ 'The same button fails consistently for multiple users.', 'The browser shows no response even after refresh.' ],
        'related_articles' => [ 'Understanding Toast Messages', 'Understanding Nonces', 'A Page Will Not Load' ],
        'permissions' => [ 'view' ],
        'proposed_actions' => [
            [ 'command' => 'run_full_diagnostics', 'title' => 'Run Diagnostics', 'summary' => 'Collect diagnostics for the inactive button workflow.', 'risk_level' => 'low', 'requires_approval' => false ],
        ],
    ],
    [
        'key' => 'page_wont_load',
        'title' => 'A Page Will Not Load',
        'classification' => 'SYSTEM',
        'module' => 'Metis',
        'module_key' => 'portal',
        'action' => 'page_load',
        'summary' => 'Page-load issues usually mean the route failed, access changed, or the page depends on a failing module or request.',
        'phrases' => [ 'a page will not load', 'page will not load', 'page wont load', 'screen stuck loading' ],
        'search_terms' => [ 'page will not load', 'screen stuck loading', 'route failed', 'page load error', 'blank page metis' ],
        'steps' => [ 'Refresh the page once.', 'Try entering the page from the main navigation instead of an old bookmark.', 'Confirm you are signed in and the session is still active.', 'Check whether the same module opens from another route.' ],
        'checks' => [ 'The route may have changed.', 'The module may be unavailable or disabled.', 'Permission or session state can block page delivery.' ],
        'admin_escalation' => [ 'The page still fails after refresh and navigation retry.', 'Multiple users report the same route failure.' ],
        'related_articles' => [ 'Using the Left Navigation Menu', 'Understanding Nonces', 'Search Shows No Results' ],
        'permissions' => [ 'view' ],
        'proposed_actions' => [
            [ 'command' => 'validate_routes', 'title' => 'Validate Routes', 'summary' => 'Check route availability for the failing page.', 'risk_level' => 'low', 'requires_approval' => false ],
            [ 'command' => 'run_full_diagnostics', 'title' => 'Run Diagnostics', 'summary' => 'Collect system diagnostics for the failing page route.', 'risk_level' => 'low', 'requires_approval' => false ],
        ],
    ],
    [
        'key' => 'search_no_results',
        'title' => 'Search Shows No Results',
        'classification' => 'WORKFLOW',
        'module' => 'Metis',
        'module_key' => 'help',
        'action' => 'search_no_results',
        'summary' => 'No-result searches usually come from overly specific wording, missing search terms, or a stale search index.',
        'phrases' => [ 'search shows no results', 'search returns nothing', 'help search no results', 'cannot find article in search' ],
        'search_terms' => [ 'search shows no results', 'search returns nothing', 'help search no results', 'cannot find article in search', 'search index stale' ],
        'steps' => [ 'Try fewer words.', 'Search by the module name.', 'Search by the task instead of the exact sentence.', 'Remove uncommon filler words.', 'Retry the search with the core nouns only.' ],
        'checks' => [ 'Search terms may be too specific.', 'Relevant help articles may be missing issue phrases.', 'The search index may need rebuilding.' ],
        'admin_escalation' => [ 'Repeated common phrases return nothing.', 'Known help articles are missing from search results.' ],
        'related_articles' => [ 'Searching Across Metis', 'Asking Hermes for Help' ],
        'permissions' => [ 'help.view' ],
        'proposed_actions' => [
            [ 'command' => 'rebuild_indexes', 'title' => 'Rebuild Help Search Index', 'summary' => 'Rebuild indexed search text so new issue phrases can be found.', 'risk_level' => 'medium', 'requires_approval' => true ],
        ],
    ],
];
