<?php
declare(strict_types=1);

namespace Metis\Hermes;

final class HermesCommandRegistry {
    /**
     * @return array<string,array<string,mixed>>
     */
    public function definitions(): array {
        $defs = [];

        foreach ( $this->requiredCommands() as $name => $spec ) {
            $defs[ $name ] = [
                'key' => $name,
                'title' => ucwords( str_replace( '_', ' ', $name ) ),
                'description' => (string) $spec['description'],
                'domain' => (string) $spec['domain'],
                'module' => (string) $spec['module'],
                'tool_key' => (string) $spec['tool_key'],
                'permission' => (string) $spec['permission'],
                'phrases' => (array) ( $spec['phrases'] ?? [] ),
                'keywords' => (array) ( $spec['keywords'] ?? [] ),
                'expects_entity' => (bool) ( $spec['expects_entity'] ?? false ),
                'supports_context' => (bool) ( $spec['supports_context'] ?? false ),
                'requires_approval' => (bool) ( $spec['requires_approval'] ?? false ),
                'read_only' => ! empty( $spec['read_only'] ),
                'worker_supported' => ! empty( $spec['worker_supported'] ),
                'input_schema' => (array) ( $spec['input_schema'] ?? [ 'type' => 'object', 'properties' => [], 'required' => [] ] ),
                'output_schema' => [ 'type' => 'object', 'required' => [ 'status' ] ],
            ];
        }

        return $defs;
    }

    /**
     * @return array<string,mixed>
     */
    public function definition( string $key ): array {
        $definitions = $this->definitions();
        return $definitions[ trim( strtolower( $key ) ) ] ?? [];
    }

    /**
     * @return array<string,array<string,mixed>>
     */
    private function requiredCommands(): array {
        $basicSchema = [
            'type' => 'object',
            'properties' => [
                'subject' => [ 'type' => 'string' ],
                'email' => [ 'type' => 'string' ],
                'roles' => [ 'type' => 'array', 'items' => [ 'type' => 'string' ] ],
                'query' => [ 'type' => 'string' ],
                'new_password' => [ 'type' => 'string' ],
                'run_uuid' => [ 'type' => 'string' ],
                'tag' => [ 'type' => 'string' ],
                'job_code' => [ 'type' => 'string' ],
                'job_type' => [ 'type' => 'string' ],
                'module_key' => [ 'type' => 'string' ],
                'file_key' => [ 'type' => 'string' ],
                'folder_id' => [ 'type' => 'string' ],
                'group_emails' => [ 'type' => 'array', 'items' => [ 'type' => 'string' ] ],
                'current_route' => [ 'type' => 'string' ],
                'current_module' => [ 'type' => 'string' ],
                'user_message' => [ 'type' => 'string' ],
                'nonce' => [ 'type' => 'string' ],
                'nonce_action' => [ 'type' => 'string' ],
            ],
            'required' => [],
        ];

        return [
            'create_user' => [ 'description' => 'Create a user.', 'domain' => 'people', 'module' => 'people', 'tool_key' => 'hermes.user.create_user', 'permission' => 'people.create', 'phrases' => [ 'create user', 'add user', 'new user' ], 'keywords' => [ 'user', 'create', 'add' ], 'expects_entity' => true, 'supports_context' => false, 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],
            'workspace_user_create' => [ 'description' => 'Create a workspace user.', 'domain' => 'people', 'module' => 'people', 'tool_key' => 'hermes.user.create_user', 'permission' => 'people.create', 'phrases' => [ 'create workspace user', 'add workspace user', 'new workspace user', 'create a workspace user', 'create workspace access' ], 'keywords' => [ 'workspace', 'user', 'create', 'add' ], 'expects_entity' => true, 'supports_context' => false, 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],
            'update_user' => [ 'description' => 'Update a user.', 'domain' => 'people', 'module' => 'people', 'tool_key' => 'hermes.user.update_user', 'permission' => 'people.edit', 'phrases' => [ 'update user', 'edit user', 'change user' ], 'keywords' => [ 'user', 'update', 'edit' ], 'expects_entity' => true, 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],
            'disable_user' => [ 'description' => 'Disable a user.', 'domain' => 'people', 'module' => 'people', 'tool_key' => 'hermes.user.disable_user', 'permission' => 'people.edit', 'phrases' => [ 'disable user', 'deactivate user', 'offboard user', 'disable ', 'deactivate ', 'offboard ' ], 'keywords' => [ 'disable', 'deactivate', 'offboard' ], 'expects_entity' => true, 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],
            'offboard_user' => [ 'description' => 'Offboard a user.', 'domain' => 'people', 'module' => 'people', 'tool_key' => 'hermes.user.disable_user', 'permission' => 'people.edit', 'phrases' => [ 'offboard user', 'disable user', 'deactivate user', 'offboard ', 'disable ', 'deactivate ' ], 'keywords' => [ 'offboard', 'disable', 'deactivate' ], 'expects_entity' => true, 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],
            'enable_user' => [ 'description' => 'Enable a user.', 'domain' => 'people', 'module' => 'people', 'tool_key' => 'hermes.user.enable_user', 'permission' => 'people.edit', 'phrases' => [ 'enable user', 'reactivate user' ], 'keywords' => [ 'enable', 'reactivate' ], 'expects_entity' => true, 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],
            'user_delete' => [ 'description' => 'Soft-delete a user.', 'domain' => 'people', 'module' => 'people', 'tool_key' => 'hermes.user.delete_user', 'permission' => 'people.edit', 'phrases' => [ 'delete user', 'remove user' ], 'keywords' => [ 'delete', 'remove', 'user' ], 'expects_entity' => true, 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],
            'user_unlock' => [ 'description' => 'Clear account-level login lockout state for a user.', 'domain' => 'people', 'module' => 'people', 'tool_key' => 'hermes.user.unlock_user', 'permission' => 'people.edit', 'phrases' => [ 'unlock user', 'unlock account' ], 'keywords' => [ 'unlock', 'user', 'account' ], 'expects_entity' => true, 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],
            'user_password_reset' => [ 'description' => 'Reset a Metis user password.', 'domain' => 'people', 'module' => 'people', 'tool_key' => 'hermes.user.reset_metis_password', 'permission' => 'people.edit', 'phrases' => [ 'reset user password', 'reset password', 'reset metis password', 'change metis password' ], 'keywords' => [ 'reset', 'password', 'metis', 'user' ], 'expects_entity' => true, 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],
            'workspace_user_password_reset' => [ 'description' => 'Reset a workspace user password.', 'domain' => 'people', 'module' => 'people', 'tool_key' => 'hermes.user.reset_workspace_password', 'permission' => 'people.workspace_manage', 'phrases' => [ 'reset workspace password', 'reset workspace user password', 'change workspace password', 'reset google workspace password' ], 'keywords' => [ 'reset', 'password', 'workspace', 'google' ], 'expects_entity' => true, 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],
            'workspace_user_update' => [ 'description' => 'Update a workspace user.', 'domain' => 'people', 'module' => 'people', 'tool_key' => 'hermes.user.update_workspace_user', 'permission' => 'people.workspace_manage', 'phrases' => [ 'update workspace user', 'edit workspace user', 'change workspace user', 'update workspace access' ], 'keywords' => [ 'workspace', 'user', 'update', 'edit', 'change' ], 'expects_entity' => true, 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],
            'workspace_user_disable' => [ 'description' => 'Disable workspace access for a user.', 'domain' => 'people', 'module' => 'people', 'tool_key' => 'hermes.user.disable_workspace_user', 'permission' => 'people.workspace_manage', 'phrases' => [ 'disable workspace user', 'disable workspace access', 'suspend workspace user', 'suspend workspace access' ], 'keywords' => [ 'workspace', 'disable', 'suspend', 'access' ], 'expects_entity' => true, 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'worker_supported' => true, 'input_schema' => $basicSchema ],
            'workspace_user_enable' => [ 'description' => 'Enable workspace access for a user.', 'domain' => 'people', 'module' => 'people', 'tool_key' => 'hermes.user.enable_workspace_user', 'permission' => 'people.workspace_manage', 'phrases' => [ 'enable workspace user', 'enable workspace access', 'restore workspace access', 'unsuspend workspace user' ], 'keywords' => [ 'workspace', 'enable', 'restore', 'unsuspend', 'access' ], 'expects_entity' => true, 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'worker_supported' => true, 'input_schema' => $basicSchema ],
            'workspace_user_delete' => [ 'description' => 'Delete a workspace user.', 'domain' => 'people', 'module' => 'people', 'tool_key' => 'hermes.user.delete_workspace_user', 'permission' => 'people.workspace_manage', 'phrases' => [ 'delete workspace user', 'remove workspace user', 'delete workspace account' ], 'keywords' => [ 'workspace', 'delete', 'remove', 'account' ], 'expects_entity' => true, 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],
            'assign_role' => [ 'description' => 'Assign role.', 'domain' => 'people', 'module' => 'people', 'tool_key' => 'hermes.user.assign_role', 'permission' => 'people.edit', 'phrases' => [ 'assign role', 'add role', 'grant role' ], 'keywords' => [ 'role', 'assign', 'grant' ], 'expects_entity' => true, 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],
            'remove_role' => [ 'description' => 'Remove role.', 'domain' => 'people', 'module' => 'people', 'tool_key' => 'hermes.user.remove_role', 'permission' => 'people.edit', 'phrases' => [ 'remove role', 'revoke role' ], 'keywords' => [ 'role', 'remove', 'revoke' ], 'expects_entity' => true, 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],
            'manage_user_roles' => [ 'description' => 'Manage user roles.', 'domain' => 'people', 'module' => 'people', 'tool_key' => 'hermes.user.assign_role', 'permission' => 'people.edit', 'phrases' => [ 'change role', 'update role', 'manage role', 'manage roles' ], 'keywords' => [ 'role', 'manage', 'change', 'update' ], 'expects_entity' => true, 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],
            'manage_workspace_groups' => [ 'description' => 'Manage Workspace groups for a user.', 'domain' => 'people', 'module' => 'people', 'tool_key' => 'hermes.user.manage_workspace_groups', 'permission' => 'people.workspace_manage', 'phrases' => [ 'manage workspace groups', 'add workspace group', 'remove workspace group', 'update workspace groups' ], 'keywords' => [ 'workspace', 'group', 'groups', 'manage', 'add', 'remove', 'update' ], 'expects_entity' => true, 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],
            'reset_user_mfa' => [ 'description' => 'Reset MFA for a user.', 'domain' => 'people', 'module' => 'people', 'tool_key' => 'hermes.user.reset_user_mfa', 'permission' => 'people.edit', 'phrases' => [ 'reset user mfa', 'reset mfa', 'reset two factor', 'reset 2fa' ], 'keywords' => [ 'reset', 'mfa', '2fa', 'two factor' ], 'expects_entity' => true, 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],
            'link_drive_folder' => [ 'description' => 'Link a Drive folder for a user.', 'domain' => 'people', 'module' => 'people', 'tool_key' => 'hermes.user.link_drive_folder', 'permission' => 'people.workspace_manage', 'phrases' => [ 'link drive folder', 'create drive folder', 'attach drive folder' ], 'keywords' => [ 'drive', 'folder', 'link', 'attach', 'create' ], 'expects_entity' => true, 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],
            'list_users' => [ 'description' => 'List users.', 'domain' => 'people', 'module' => 'people', 'tool_key' => 'hermes.user.list_users', 'permission' => 'people.view', 'phrases' => [ 'list users', 'show users', 'get users' ], 'keywords' => [ 'list', 'users', 'show' ], 'expects_entity' => false, 'supports_context' => false, 'requires_approval' => false, 'read_only' => true, 'input_schema' => $basicSchema ],
            'get_user' => [ 'description' => 'Get user.', 'domain' => 'people', 'module' => 'people', 'tool_key' => 'hermes.user.get_user', 'permission' => 'people.view', 'phrases' => [ 'get user', 'show user', 'find user' ], 'keywords' => [ 'user', 'show', 'find' ], 'expects_entity' => true, 'supports_context' => true, 'requires_approval' => false, 'read_only' => true, 'input_schema' => $basicSchema ],
            'lookup_profile' => [ 'description' => 'Lookup profile.', 'domain' => 'directory', 'module' => 'people', 'tool_key' => 'hermes.directory.lookup_profile', 'permission' => 'people.view', 'phrases' => [ 'who is', 'look up', 'lookup profile', 'find person', 'find contact' ], 'keywords' => [ 'who', 'profile', 'person', 'contact', 'find' ], 'expects_entity' => true, 'supports_context' => true, 'requires_approval' => false, 'read_only' => true, 'input_schema' => [ 'type' => 'object', 'properties' => [ 'profile_request' => [ 'type' => 'object' ] ], 'required' => [ 'profile_request' ] ] ],
            'get_entity_attribute' => [ 'description' => 'Get entity attribute.', 'domain' => 'directory', 'module' => 'people', 'tool_key' => 'hermes.directory.get_entity_attribute', 'permission' => 'people.view', 'phrases' => [ 'what is', 'email for', 'phone for', 'address for' ], 'keywords' => [ 'email', 'phone', 'address', 'name' ], 'expects_entity' => true, 'supports_context' => true, 'requires_approval' => false, 'read_only' => true, 'input_schema' => [ 'type' => 'object', 'properties' => [ 'attribute_request' => [ 'type' => 'object' ] ], 'required' => [ 'attribute_request' ] ] ],
            'resolve_help_issue' => [ 'description' => 'Resolve a user help issue from natural language.', 'domain' => 'help', 'module' => 'help', 'tool_key' => 'hermes.help.resolve_issue', 'permission' => 'help.view', 'phrases' => [ "i can't", 'i cant', "don't see", 'do not see', "won't send", 'will not load', 'permission denied', 'button does nothing', 'search shows no results', 'how do i', 'how can i', 'where do i', 'why can\'t i', 'why cant i' ], 'keywords' => [ 'cannot', "can't", 'missing', 'button', 'publish', 'report', 'page', 'email', 'send', 'save', 'load', 'create', 'edit', 'run', 'access' ], 'expects_entity' => false, 'supports_context' => true, 'requires_approval' => false, 'read_only' => true, 'input_schema' => [ 'type' => 'object', 'properties' => [ 'user_message' => [ 'type' => 'string' ], 'current_route' => [ 'type' => 'string' ], 'current_module' => [ 'type' => 'string' ], 'session_context' => [ 'type' => 'object' ] ], 'required' => [ 'user_message' ] ] ],
            'diagnose_permissions' => [ 'description' => 'Diagnose permissions.', 'domain' => 'security', 'module' => 'people', 'tool_key' => 'hermes.security.diagnose_permissions', 'permission' => 'system.diagnostics.view', 'phrases' => [ 'diagnose permissions', 'why can', 'why cant', 'access denied' ], 'keywords' => [ 'permissions', 'access', 'denied' ], 'expects_entity' => false, 'supports_context' => true, 'requires_approval' => false, 'read_only' => true, 'input_schema' => [ 'type' => 'object', 'properties' => [ 'diagnostic_request' => [ 'type' => 'object' ] ], 'required' => [ 'diagnostic_request' ] ] ],
            'query_giving_summary' => [ 'description' => 'Query giving summary.', 'domain' => 'donations', 'module' => 'donations', 'tool_key' => 'hermes.donations.query_giving_summary', 'permission' => 'directory.lookup', 'phrases' => [ 'giving summary', 'total raised', 'donations summary' ], 'keywords' => [ 'giving', 'donations', 'raised' ], 'expects_entity' => false, 'supports_context' => false, 'requires_approval' => false, 'read_only' => true, 'input_schema' => [ 'type' => 'object', 'properties' => [ 'giving_request' => [ 'type' => 'object' ] ], 'required' => [] ] ],
            'query_capability_actors' => [ 'description' => 'Query capability actors.', 'domain' => 'security', 'module' => 'people', 'tool_key' => 'hermes.security.query_capability_actors', 'permission' => 'system.diagnostics.view', 'phrases' => [ 'who can', 'who has access', 'who has permission', 'who has board access', 'who can access board', 'who can view board drive' ], 'keywords' => [ 'who', 'permission', 'access', 'board' ], 'expects_entity' => false, 'supports_context' => false, 'requires_approval' => false, 'read_only' => true, 'input_schema' => [ 'type' => 'object', 'properties' => [ 'capability_request' => [ 'type' => 'object' ] ], 'required' => [ 'capability_request' ] ] ],

            'campaign_create' => [ 'description' => 'Create a campaign.', 'domain' => 'campaign', 'module' => 'newsletter', 'tool_key' => 'hermes.campaign.create_campaign', 'permission' => 'newsletter.create', 'phrases' => [ 'create campaign', 'new campaign', 'create newsletter campaign' ], 'keywords' => [ 'campaign', 'create', 'newsletter' ], 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],
            'campaign_update' => [ 'description' => 'Update a campaign.', 'domain' => 'campaign', 'module' => 'newsletter', 'tool_key' => 'hermes.campaign.update_campaign', 'permission' => 'newsletter.edit', 'phrases' => [ 'update campaign', 'edit campaign', 'change campaign' ], 'keywords' => [ 'campaign', 'update', 'edit' ], 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],
            'campaign_publish' => [ 'description' => 'Publish a campaign.', 'domain' => 'campaign', 'module' => 'newsletter', 'tool_key' => 'hermes.campaign.publish_campaign', 'permission' => 'newsletter.edit', 'phrases' => [ 'publish campaign', 'send campaign', 'launch campaign' ], 'keywords' => [ 'campaign', 'publish', 'send', 'launch' ], 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'worker_supported' => true, 'input_schema' => $basicSchema ],
            'campaign_archive' => [ 'description' => 'Archive a campaign.', 'domain' => 'campaign', 'module' => 'newsletter', 'tool_key' => 'hermes.campaign.archive_campaign', 'permission' => 'newsletter.edit', 'phrases' => [ 'archive campaign' ], 'keywords' => [ 'campaign', 'archive' ], 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],
            'campaign_delete' => [ 'description' => 'Delete a campaign.', 'domain' => 'campaign', 'module' => 'newsletter', 'tool_key' => 'hermes.campaign.delete_campaign', 'permission' => 'newsletter.delete', 'phrases' => [ 'delete campaign' ], 'keywords' => [ 'campaign', 'delete' ], 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],
            'newsletter_create' => [ 'description' => 'Create a newsletter.', 'domain' => 'newsletter', 'module' => 'newsletter', 'tool_key' => 'hermes.newsletter.create_newsletter', 'permission' => 'newsletter.create', 'phrases' => [ 'create newsletter', 'new newsletter' ], 'keywords' => [ 'newsletter', 'create' ], 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],
            'newsletter_send' => [ 'description' => 'Send a newsletter.', 'domain' => 'newsletter', 'module' => 'newsletter', 'tool_key' => 'hermes.newsletter.send_newsletter', 'permission' => 'newsletter.edit', 'phrases' => [ 'send newsletter', 'publish newsletter' ], 'keywords' => [ 'newsletter', 'send', 'publish' ], 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'worker_supported' => true, 'input_schema' => $basicSchema ],
            'newsletter_schedule' => [ 'description' => 'Schedule a newsletter.', 'domain' => 'newsletter', 'module' => 'newsletter', 'tool_key' => 'hermes.newsletter.schedule_newsletter', 'permission' => 'newsletter.edit', 'phrases' => [ 'schedule newsletter' ], 'keywords' => [ 'newsletter', 'schedule' ], 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'worker_supported' => true, 'input_schema' => $basicSchema ],
            'newsletter_cancel' => [ 'description' => 'Cancel a scheduled newsletter.', 'domain' => 'newsletter', 'module' => 'newsletter', 'tool_key' => 'hermes.newsletter.cancel_newsletter', 'permission' => 'newsletter.edit', 'phrases' => [ 'cancel newsletter', 'unschedule newsletter', 'cancel scheduled newsletter' ], 'keywords' => [ 'newsletter', 'cancel', 'unschedule', 'scheduled' ], 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],
            'newsletter_delete' => [ 'description' => 'Delete a newsletter.', 'domain' => 'newsletter', 'module' => 'newsletter', 'tool_key' => 'hermes.newsletter.delete_newsletter', 'permission' => 'newsletter.delete', 'phrases' => [ 'delete newsletter' ], 'keywords' => [ 'newsletter', 'delete' ], 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],

            'run_backup' => [ 'description' => 'Start a system backup.', 'domain' => 'system', 'module' => 'settings', 'tool_key' => 'hermes.system.start_backup', 'permission' => 'system.backup.execute', 'phrases' => [ 'run backup', 'start backup', 'backup now', 'run a backup' ], 'keywords' => [ 'backup', 'run', 'start' ], 'requires_approval' => true, 'read_only' => false, 'worker_supported' => true, 'input_schema' => $basicSchema ],
            'backup_start' => [ 'description' => 'Start a system backup.', 'domain' => 'system', 'module' => 'settings', 'tool_key' => 'hermes.system.start_backup', 'permission' => 'system.backup.execute', 'phrases' => [ 'backup start', 'start backup', 'begin backup', 'backup now' ], 'keywords' => [ 'backup', 'start', 'begin' ], 'requires_approval' => true, 'read_only' => false, 'worker_supported' => true, 'input_schema' => $basicSchema ],
            'backup_restore' => [ 'description' => 'Restore a backup run.', 'domain' => 'system', 'module' => 'settings', 'tool_key' => 'hermes.system.restore_backup', 'permission' => 'system.backup.execute', 'phrases' => [ 'restore backup', 'backup restore' ], 'keywords' => [ 'backup', 'restore' ], 'requires_approval' => true, 'read_only' => false, 'worker_supported' => true, 'input_schema' => $basicSchema ],
            'backup_validate' => [ 'description' => 'Validate a backup run.', 'domain' => 'system', 'module' => 'settings', 'tool_key' => 'hermes.system.validate_backup', 'permission' => 'system.backup.execute', 'phrases' => [ 'validate backup', 'backup validate', 'verify backup', 'check backup integrity' ], 'keywords' => [ 'backup', 'validate', 'verify', 'integrity' ], 'requires_approval' => true, 'read_only' => false, 'worker_supported' => true, 'input_schema' => $basicSchema ],
            'clear_cache' => [ 'description' => 'Clear cache.', 'domain' => 'system', 'module' => 'settings', 'tool_key' => 'hermes.system.clear_cache', 'permission' => 'system.backup.execute', 'phrases' => [ 'clear cache', 'flush cache' ], 'keywords' => [ 'cache', 'clear', 'flush' ], 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],
            'cache_clear' => [ 'description' => 'Clear cache.', 'domain' => 'system', 'module' => 'settings', 'tool_key' => 'hermes.system.clear_cache', 'permission' => 'system.backup.execute', 'phrases' => [ 'cache clear', 'clear cache', 'flush cache' ], 'keywords' => [ 'cache', 'clear', 'flush' ], 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],
            'rebuild_indexes' => [ 'description' => 'Rebuild indexes.', 'domain' => 'system', 'module' => 'settings', 'tool_key' => 'hermes.system.rebuild_indexes', 'permission' => 'system.backup.execute', 'phrases' => [ 'rebuild indexes', 'reindex' ], 'keywords' => [ 'indexes', 'rebuild', 'reindex' ], 'requires_approval' => true, 'read_only' => false, 'worker_supported' => false, 'input_schema' => $basicSchema ],
            'reload_config' => [ 'description' => 'Reload config.', 'domain' => 'system', 'module' => 'settings', 'tool_key' => 'hermes.system.reload_config', 'permission' => 'system.backup.execute', 'phrases' => [ 'reload config', 'reload configuration' ], 'keywords' => [ 'reload', 'config' ], 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],
            'get_system_status' => [ 'description' => 'Get system status.', 'domain' => 'system', 'module' => 'settings', 'tool_key' => 'hermes.system.get_system_status', 'permission' => 'system.diagnostics.view', 'phrases' => [ 'system status', 'status report' ], 'keywords' => [ 'system', 'status' ], 'requires_approval' => false, 'read_only' => true, 'input_schema' => $basicSchema ],
            'check_system_updates' => [ 'description' => 'Check for available system updates.', 'domain' => 'system', 'module' => 'settings', 'tool_key' => 'hermes.system.check_updates', 'permission' => 'system.backup.execute', 'phrases' => [ 'check for system updates', 'check system updates', 'check for updates', 'check updates', 'system update check', 'release check', 'refresh releases' ], 'keywords' => [ 'check', 'updates', 'update', 'release', 'system' ], 'requires_approval' => false, 'read_only' => true, 'input_schema' => $basicSchema ],
            'update_check' => [ 'description' => 'Check for available system updates.', 'domain' => 'system', 'module' => 'settings', 'tool_key' => 'hermes.system.check_updates', 'permission' => 'system.backup.execute', 'phrases' => [ 'update check', 'check updates', 'check for updates', 'release check' ], 'keywords' => [ 'update', 'check', 'release' ], 'requires_approval' => false, 'read_only' => true, 'input_schema' => $basicSchema ],
            'aut_update_check' => [ 'description' => 'Check for available system updates.', 'domain' => 'system', 'module' => 'settings', 'tool_key' => 'hermes.system.check_updates', 'permission' => 'system.backup.execute', 'phrases' => [ 'aut-update-check', 'automatic update check' ], 'keywords' => [ 'aut', 'update', 'check' ], 'requires_approval' => false, 'read_only' => true, 'input_schema' => $basicSchema ],
            'update_install' => [ 'description' => 'Install a trusted system update.', 'domain' => 'system', 'module' => 'settings', 'tool_key' => 'hermes.system.install_update', 'permission' => 'system.backup.execute', 'phrases' => [ 'install update', 'apply update', 'update install', 'install system update', 'apply system update' ], 'keywords' => [ 'install', 'update', 'apply', 'release' ], 'requires_approval' => true, 'read_only' => false, 'worker_supported' => true, 'input_schema' => $basicSchema ],
            'aut_update_install' => [ 'description' => 'Install a trusted system update.', 'domain' => 'system', 'module' => 'settings', 'tool_key' => 'hermes.system.install_update', 'permission' => 'system.backup.execute', 'phrases' => [ 'aut-update-install', 'automatic update install' ], 'keywords' => [ 'aut', 'update', 'install' ], 'requires_approval' => true, 'read_only' => false, 'worker_supported' => true, 'input_schema' => $basicSchema ],
            'release_rollback' => [ 'description' => 'Rollback to the previous trusted release.', 'domain' => 'system', 'module' => 'settings', 'tool_key' => 'hermes.system.rollback_release', 'permission' => 'system.backup.execute', 'phrases' => [ 'release rollback', 'rollback release', 'system rollback', 'rollback system update' ], 'keywords' => [ 'release', 'rollback', 'system', 'update' ], 'requires_approval' => true, 'read_only' => false, 'worker_supported' => true, 'input_schema' => $basicSchema ],
            'drive_sync' => [ 'description' => 'Queue sync across configured drives.', 'domain' => 'system', 'module' => 'settings', 'tool_key' => 'hermes.system.sync_drive', 'permission' => 'system.backup.execute', 'phrases' => [ 'drive sync', 'sync drives', 'sync drive' ], 'keywords' => [ 'drive', 'sync' ], 'requires_approval' => true, 'read_only' => false, 'worker_supported' => true, 'input_schema' => $basicSchema ],
            'calendar_sync' => [ 'description' => 'Queue sync across configured calendars.', 'domain' => 'system', 'module' => 'settings', 'tool_key' => 'hermes.system.sync_calendar', 'permission' => 'system.backup.execute', 'phrases' => [ 'calendar sync', 'sync calendars', 'sync calendar' ], 'keywords' => [ 'calendar', 'sync' ], 'requires_approval' => true, 'read_only' => false, 'worker_supported' => true, 'input_schema' => $basicSchema ],
            'queue_drain' => [ 'description' => 'Drain the operations queue.', 'domain' => 'system', 'module' => 'settings', 'tool_key' => 'hermes.system.drain_queue', 'permission' => 'system.backup.execute', 'phrases' => [ 'queue drain', 'drain queue' ], 'keywords' => [ 'queue', 'drain' ], 'requires_approval' => true, 'read_only' => false, 'worker_supported' => true, 'input_schema' => $basicSchema ],
            'integrity_baseline' => [ 'description' => 'Build a fresh integrity baseline.', 'domain' => 'system', 'module' => 'settings', 'tool_key' => 'hermes.system.integrity_baseline', 'permission' => 'system.backup.execute', 'phrases' => [ 'integrity baseline', 'build integrity baseline', 'rebuild integrity baseline' ], 'keywords' => [ 'integrity', 'baseline', 'build', 'rebuild' ], 'requires_approval' => true, 'read_only' => false, 'worker_supported' => true, 'input_schema' => $basicSchema ],
            'module_compliance_audit' => [ 'description' => 'Run a module compliance audit.', 'domain' => 'system', 'module' => 'settings', 'tool_key' => 'hermes.system.module_compliance_audit', 'permission' => 'system.backup.execute', 'phrases' => [ 'module compliance audit', 'run module compliance audit', 'audit module compliance' ], 'keywords' => [ 'module', 'compliance', 'audit' ], 'requires_approval' => true, 'read_only' => false, 'worker_supported' => true, 'input_schema' => $basicSchema ],
            'board_workspace_prepare' => [ 'description' => 'Prepare a board meeting workspace.', 'domain' => 'system', 'module' => 'board', 'tool_key' => 'hermes.system.prepare_board_workspace', 'permission' => 'system.backup.execute', 'phrases' => [ 'prepare board workspace', 'board workspace prepare', 'prepare meeting workspace' ], 'keywords' => [ 'board', 'workspace', 'prepare', 'meeting' ], 'requires_approval' => true, 'read_only' => false, 'worker_supported' => true, 'input_schema' => $basicSchema ],

            'run_full_diagnostics' => [ 'description' => 'Run diagnostics.', 'domain' => 'diagnostics', 'module' => 'hermes', 'tool_key' => 'hermes.diagnostics.run_full_diagnostics', 'permission' => 'system.diagnostics.view', 'phrases' => [ 'run diagnostics', 'run diagnostic', 'full diagnostics', 'full diagnostic', 'system diagnostics', 'system diagnostic' ], 'keywords' => [ 'diagnostics', 'diagnostic', 'run', 'full', 'system' ], 'requires_approval' => false, 'read_only' => true, 'worker_supported' => true, 'input_schema' => $basicSchema ],
            'diagnostics_run' => [ 'description' => 'Run diagnostics.', 'domain' => 'diagnostics', 'module' => 'hermes', 'tool_key' => 'hermes.diagnostics.run_full_diagnostics', 'permission' => 'system.diagnostics.view', 'phrases' => [ 'diagnostics run', 'run diagnostics', 'system diagnostics' ], 'keywords' => [ 'diagnostics', 'run', 'system' ], 'requires_approval' => false, 'read_only' => true, 'worker_supported' => true, 'input_schema' => $basicSchema ],
            'check_modules' => [ 'description' => 'Check module status.', 'domain' => 'diagnostics', 'module' => 'hermes', 'tool_key' => 'hermes.diagnostics.check_modules', 'permission' => 'system.diagnostics.view', 'phrases' => [ 'module diagnostics', 'module diagnostic', 'run module diagnostics', 'run module diagnostic', 'check modules', 'check module status', 'module health' ], 'keywords' => [ 'module', 'modules', 'diagnostics', 'diagnostic', 'health' ], 'requires_approval' => false, 'read_only' => true, 'input_schema' => $basicSchema ],
            'scan_integrity' => [ 'description' => 'Scan integrity.', 'domain' => 'diagnostics', 'module' => 'hermes', 'tool_key' => 'hermes.diagnostics.scan_integrity', 'permission' => 'system.diagnostics.view', 'phrases' => [ 'scan integrity', 'integrity scan', 'integrity diagnostics' ], 'keywords' => [ 'integrity', 'scan' ], 'requires_approval' => false, 'read_only' => true, 'worker_supported' => false, 'input_schema' => $basicSchema ],
            'check_db' => [ 'description' => 'Check DB.', 'domain' => 'diagnostics', 'module' => 'hermes', 'tool_key' => 'hermes.diagnostics.check_db', 'permission' => 'system.diagnostics.view', 'phrases' => [ 'check db', 'check database', 'db check', 'database check', 'database health', 'check database health' ], 'keywords' => [ 'db', 'database', 'health' ], 'requires_approval' => false, 'read_only' => true, 'input_schema' => $basicSchema ],
            'check_workers' => [ 'description' => 'Check workers.', 'domain' => 'diagnostics', 'module' => 'hermes', 'tool_key' => 'hermes.diagnostics.check_workers', 'permission' => 'system.diagnostics.view', 'phrases' => [ 'check workers', 'worker health', 'worker diagnostics', 'check jobs', 'check queue', 'check worker queue', 'queue health' ], 'keywords' => [ 'worker', 'jobs', 'queue' ], 'requires_approval' => false, 'read_only' => true, 'input_schema' => $basicSchema ],

            'recover_module' => [ 'description' => 'Recover module.', 'domain' => 'recovery', 'module' => 'settings', 'tool_key' => 'hermes.recovery.recover_module', 'permission' => 'system.backup.execute', 'phrases' => [ 'recover module' ], 'keywords' => [ 'recover', 'module' ], 'expects_entity' => false, 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'worker_supported' => false, 'input_schema' => $basicSchema ],
            'restore_file' => [ 'description' => 'Restore file.', 'domain' => 'recovery', 'module' => 'settings', 'tool_key' => 'hermes.recovery.restore_file', 'permission' => 'system.backup.execute', 'phrases' => [ 'restore file' ], 'keywords' => [ 'restore', 'file' ], 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'worker_supported' => false, 'input_schema' => $basicSchema ],
            'rollback_module' => [ 'description' => 'Rollback module.', 'domain' => 'recovery', 'module' => 'settings', 'tool_key' => 'hermes.recovery.rollback_module', 'permission' => 'system.backup.execute', 'phrases' => [ 'rollback module' ], 'keywords' => [ 'rollback', 'module' ], 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'worker_supported' => false, 'input_schema' => $basicSchema ],

            'enable_module' => [ 'description' => 'Enable module.', 'domain' => 'module', 'module' => 'settings', 'tool_key' => 'hermes.module.enable_module', 'permission' => 'system.backup.execute', 'phrases' => [ 'enable module' ], 'keywords' => [ 'enable', 'module' ], 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'worker_supported' => false, 'input_schema' => $basicSchema ],
            'disable_module' => [ 'description' => 'Disable module.', 'domain' => 'module', 'module' => 'settings', 'tool_key' => 'hermes.module.disable_module', 'permission' => 'system.backup.execute', 'phrases' => [ 'disable module' ], 'keywords' => [ 'disable', 'module' ], 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'worker_supported' => false, 'input_schema' => $basicSchema ],
            'install_module' => [ 'description' => 'Install module.', 'domain' => 'module', 'module' => 'settings', 'tool_key' => 'hermes.module.install_module', 'permission' => 'system.backup.execute', 'phrases' => [ 'install module' ], 'keywords' => [ 'install', 'module' ], 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'worker_supported' => false, 'input_schema' => $basicSchema ],
            'update_module' => [ 'description' => 'Update module.', 'domain' => 'module', 'module' => 'settings', 'tool_key' => 'hermes.module.update_module', 'permission' => 'system.backup.execute', 'phrases' => [ 'update module' ], 'keywords' => [ 'update', 'module' ], 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'worker_supported' => false, 'input_schema' => $basicSchema ],

            'export_data' => [ 'description' => 'Export data.', 'domain' => 'data', 'module' => 'reports', 'tool_key' => 'hermes.data.export_data', 'permission' => 'reports.view', 'phrases' => [ 'export data' ], 'keywords' => [ 'export', 'data' ], 'requires_approval' => false, 'read_only' => true, 'worker_supported' => false, 'input_schema' => $basicSchema ],
            'import_data' => [ 'description' => 'Import data.', 'domain' => 'data', 'module' => 'import', 'tool_key' => 'hermes.data.import_data', 'permission' => 'edit', 'phrases' => [ 'import data' ], 'keywords' => [ 'import', 'data' ], 'requires_approval' => true, 'read_only' => false, 'worker_supported' => false, 'input_schema' => $basicSchema ],
            'deduplicate' => [ 'description' => 'Deduplicate data.', 'domain' => 'data', 'module' => 'contacts', 'tool_key' => 'hermes.data.deduplicate', 'permission' => 'edit', 'phrases' => [ 'deduplicate', 'dedupe' ], 'keywords' => [ 'deduplicate', 'dedupe', 'duplicates' ], 'requires_approval' => true, 'read_only' => false, 'worker_supported' => false, 'input_schema' => $basicSchema ],

            'create_job' => [ 'description' => 'Create job.', 'domain' => 'workers', 'module' => 'settings', 'tool_key' => 'hermes.workers.create_job', 'permission' => 'system.backup.execute', 'phrases' => [ 'create job', 'queue job' ], 'keywords' => [ 'job', 'queue', 'create' ], 'requires_approval' => true, 'read_only' => false, 'worker_supported' => true, 'input_schema' => $basicSchema ],
            'cancel_job' => [ 'description' => 'Cancel job.', 'domain' => 'workers', 'module' => 'settings', 'tool_key' => 'hermes.workers.cancel_job', 'permission' => 'system.backup.execute', 'phrases' => [ 'cancel job' ], 'keywords' => [ 'cancel', 'job' ], 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],
            'retry_job' => [ 'description' => 'Retry job.', 'domain' => 'workers', 'module' => 'settings', 'tool_key' => 'hermes.workers.retry_job', 'permission' => 'system.backup.execute', 'phrases' => [ 'retry job' ], 'keywords' => [ 'retry', 'job' ], 'supports_context' => true, 'requires_approval' => true, 'read_only' => false, 'input_schema' => $basicSchema ],
            'list_jobs' => [ 'description' => 'List jobs.', 'domain' => 'workers', 'module' => 'settings', 'tool_key' => 'hermes.workers.list_jobs', 'permission' => 'system.diagnostics.view', 'phrases' => [ 'list jobs', 'show jobs' ], 'keywords' => [ 'list', 'jobs' ], 'requires_approval' => false, 'read_only' => true, 'input_schema' => $basicSchema ],

            'audit_permissions' => [ 'description' => 'Audit permissions.', 'domain' => 'security', 'module' => 'people', 'tool_key' => 'hermes.security.audit_permissions', 'permission' => 'system.diagnostics.view', 'phrases' => [ 'audit permissions', 'permission audit' ], 'keywords' => [ 'audit', 'permissions' ], 'requires_approval' => false, 'read_only' => true, 'input_schema' => $basicSchema ],
            'verify_integrity' => [ 'description' => 'Verify integrity.', 'domain' => 'security', 'module' => 'settings', 'tool_key' => 'hermes.security.verify_integrity', 'permission' => 'system.diagnostics.view', 'phrases' => [ 'verify integrity' ], 'keywords' => [ 'verify', 'integrity' ], 'requires_approval' => false, 'read_only' => true, 'worker_supported' => false, 'input_schema' => $basicSchema ],
            'rotate_keys' => [ 'description' => 'Rotate keys.', 'domain' => 'security', 'module' => 'settings', 'tool_key' => 'hermes.security.rotate_keys', 'permission' => 'system.backup.execute', 'phrases' => [ 'rotate keys', 'key rotation' ], 'keywords' => [ 'rotate', 'keys' ], 'requires_approval' => true, 'read_only' => false, 'worker_supported' => false, 'input_schema' => $basicSchema ],

            'validate_routes' => [ 'description' => 'Validate routes.', 'domain' => 'metis', 'module' => 'core', 'tool_key' => 'hermes.metis.validate_routes', 'permission' => 'system.diagnostics.view', 'phrases' => [ 'validate routes' ], 'keywords' => [ 'validate', 'routes' ], 'requires_approval' => false, 'read_only' => true, 'input_schema' => $basicSchema ],
            'verify_nonce' => [ 'description' => 'Verify nonce.', 'domain' => 'metis', 'module' => 'core', 'tool_key' => 'hermes.metis.verify_nonce', 'permission' => 'system.diagnostics.view', 'phrases' => [ 'verify nonce' ], 'keywords' => [ 'verify', 'nonce' ], 'requires_approval' => false, 'read_only' => true, 'input_schema' => $basicSchema ],
            'run_enclave_test' => [ 'description' => 'Run enclave test.', 'domain' => 'metis', 'module' => 'core', 'tool_key' => 'hermes.metis.run_enclave_test', 'permission' => 'system.diagnostics.view', 'phrases' => [ 'run enclave test', 'enclave test' ], 'keywords' => [ 'enclave', 'test' ], 'requires_approval' => false, 'read_only' => true, 'input_schema' => $basicSchema ],
        ];
    }
}
