<?php
declare(strict_types=1);

namespace Metis\Hermes;

final class HermesCommandRegistry {
    public function definitions(): array {
        return [
            'run_backup' => [
                'key' => 'run_backup',
                'tool_key' => 'system.action.run_backup',
                'version' => 1,
                'category' => 'action_proposal',
                'title' => 'Run System Backup',
                'domain' => 'system',
                'module' => 'settings',
                'description' => 'Prepare and execute a privileged backup workflow through the Metis backup service.',
                'read_only' => false,
                'cache_ttl_seconds' => 0,
                'enclave_operation' => 'hermes.command.run_backup',
                'idempotency_strategy' => 'manual_trigger',
                'diagnostic_tags' => [ 'system', 'backup' ],
                'input_schema' => [
                    'type' => 'object',
                    'properties' => [],
                    'required' => [],
                ],
                'output_schema' => [
                    'type' => 'object',
                    'required' => [ 'status' ],
                ],
                'service' => [
                    'service' => 'hermes_system_ops',
                    'method' => 'runBackup',
                ],
                'permission' => 'system.backup.execute',
                'permission_requirements' => [
                    [
                        'type' => 'role_permission',
                        'permission_key' => 'system.backup.execute',
                        'allowed_roles' => [ 'administrator', 'board' ],
                    ],
                ],
                'context' => [ 'system', 'backup' ],
                'steps' => [
                    'validate_backup_configuration',
                    'queue_backup_job',
                    'confirm_job_enqueued',
                ],
            ],
            'sync_drive' => [
                'key' => 'sync_drive',
                'tool_key' => 'system.action.sync_drive',
                'version' => 1,
                'category' => 'action_proposal',
                'title' => 'Sync Drive',
                'domain' => 'system',
                'module' => 'drive',
                'description' => 'Queue a Drive synchronization run for configured drives.',
                'read_only' => false,
                'cache_ttl_seconds' => 0,
                'enclave_operation' => 'hermes.command.sync_drive',
                'idempotency_strategy' => 'manual_trigger',
                'diagnostic_tags' => [ 'system', 'drive', 'sync' ],
                'input_schema' => [ 'type' => 'object', 'properties' => [], 'required' => [] ],
                'output_schema' => [ 'type' => 'object', 'required' => [ 'status' ] ],
                'service' => [
                    'service' => 'hermes_system_ops',
                    'method' => 'syncDrive',
                ],
                'permission' => 'system.backup.execute',
                'permission_requirements' => [
                    [
                        'type' => 'role_permission',
                        'permission_key' => 'system.backup.execute',
                        'allowed_roles' => [ 'administrator', 'board' ],
                    ],
                ],
                'context' => [ 'system', 'drive' ],
                'steps' => [ 'validate_drive_sync_configuration', 'queue_drive_sync_job', 'confirm_job_enqueued' ],
            ],
            'sync_calendar' => [
                'key' => 'sync_calendar',
                'tool_key' => 'system.action.sync_calendar',
                'version' => 1,
                'category' => 'action_proposal',
                'title' => 'Sync Calendar',
                'domain' => 'system',
                'module' => 'calendar',
                'description' => 'Queue a Calendar synchronization run for configured calendars.',
                'read_only' => false,
                'cache_ttl_seconds' => 0,
                'enclave_operation' => 'hermes.command.sync_calendar',
                'idempotency_strategy' => 'manual_trigger',
                'diagnostic_tags' => [ 'system', 'calendar', 'sync' ],
                'input_schema' => [ 'type' => 'object', 'properties' => [], 'required' => [] ],
                'output_schema' => [ 'type' => 'object', 'required' => [ 'status' ] ],
                'service' => [
                    'service' => 'hermes_system_ops',
                    'method' => 'syncCalendar',
                ],
                'permission' => 'system.backup.execute',
                'permission_requirements' => [
                    [
                        'type' => 'role_permission',
                        'permission_key' => 'system.backup.execute',
                        'allowed_roles' => [ 'administrator', 'board' ],
                    ],
                ],
                'context' => [ 'system', 'calendar' ],
                'steps' => [ 'validate_calendar_sync_configuration', 'queue_calendar_sync_job', 'confirm_job_enqueued' ],
            ],
            'clear_cache' => [
                'key' => 'clear_cache',
                'tool_key' => 'system.action.clear_cache',
                'version' => 1,
                'category' => 'action_proposal',
                'title' => 'Clear Cache',
                'domain' => 'system',
                'module' => 'settings',
                'description' => 'Queue a runtime cache clear operation.',
                'read_only' => false,
                'cache_ttl_seconds' => 0,
                'enclave_operation' => 'hermes.command.clear_cache',
                'idempotency_strategy' => 'manual_trigger',
                'diagnostic_tags' => [ 'system', 'cache' ],
                'input_schema' => [ 'type' => 'object', 'properties' => [], 'required' => [] ],
                'output_schema' => [ 'type' => 'object', 'required' => [ 'status' ] ],
                'service' => [
                    'service' => 'hermes_system_ops',
                    'method' => 'clearCache',
                ],
                'permission' => 'system.backup.execute',
                'permission_requirements' => [
                    [
                        'type' => 'role_permission',
                        'permission_key' => 'system.backup.execute',
                        'allowed_roles' => [ 'administrator', 'board' ],
                    ],
                ],
                'context' => [ 'system' ],
                'steps' => [ 'queue_cache_clear_job', 'confirm_job_enqueued' ],
            ],
            'send_announcement' => [
                'key' => 'send_announcement',
                'tool_key' => 'communications.action.send_announcement',
                'version' => 1,
                'category' => 'action_proposal',
                'title' => 'Send Announcement',
                'domain' => 'communications',
                'module' => 'newsletter',
                'description' => 'Prepare an announcement send through the communications service for approval-first execution.',
                'read_only' => false,
                'cache_ttl_seconds' => 0,
                'enclave_operation' => 'hermes.command.send_announcement',
                'idempotency_strategy' => 'request_hash',
                'diagnostic_tags' => [ 'communications', 'announcement' ],
                'input_schema' => [
                    'type' => 'object',
                    'properties' => [
                        'announcement' => [
                            'type' => 'object',
                            'required' => [ 'subject', 'body' ],
                            'properties' => [
                                'subject' => [ 'type' => 'string' ],
                                'body' => [ 'type' => 'string' ],
                            ],
                        ],
                    ],
                    'required' => [ 'announcement' ],
                ],
                'output_schema' => [
                    'type' => 'object',
                    'required' => [ 'status' ],
                ],
                'service' => [
                    'service' => 'communications',
                    'method' => 'sendAnnouncement',
                    'arguments_from_payload' => [ 'announcement' ],
                ],
                'permission' => 'communications.announcement.send',
                'permission_requirements' => [
                    [
                        'type' => 'module_action',
                        'module' => 'newsletter',
                        'action' => 'create',
                        'permission_key' => 'communications.announcement.send',
                    ],
                ],
                'context' => [ 'contacts', 'communications' ],
                'steps' => [
                    'resolve_target_audience',
                    'prepare_announcement_payload',
                    'dispatch_announcement',
                ],
            ],
            'diagnose_permissions' => [
                'key' => 'diagnose_permissions',
                'tool_key' => 'security.diagnostic.diagnose_permissions',
                'version' => 1,
                'category' => 'diagnostic',
                'title' => 'Diagnose Permissions',
                'domain' => 'security',
                'module' => 'people',
                'description' => 'Run a bounded permission diagnostic against identity, grants, and inheritance evidence.',
                'read_only' => true,
                'cache_ttl_seconds' => 60,
                'enclave_operation' => '',
                'idempotency_strategy' => 'request_hash',
                'diagnostic_tags' => [ 'security', 'permissions' ],
                'input_schema' => [
                    'type' => 'object',
                    'properties' => [
                        'diagnostic_request' => [
                            'type' => 'object',
                            'required' => [ 'query' ],
                            'properties' => [
                                'query' => [ 'type' => 'string' ],
                            ],
                        ],
                    ],
                    'required' => [ 'diagnostic_request' ],
                ],
                'output_schema' => [
                    'type' => 'object',
                    'required' => [ 'status' ],
                ],
                'service' => [
                    'service' => 'security_diagnostics',
                    'method' => 'diagnosePermissions',
                    'arguments_from_payload' => [ 'diagnostic_request' ],
                ],
                'permission' => 'system.diagnostics.view',
                'permission_requirements' => [
                    [
                        'type' => 'role_permission',
                        'permission_key' => 'system.diagnostics.view',
                        'allowed_roles' => [ 'administrator', 'board', 'donor_admin' ],
                    ],
                ],
                'context' => [ 'people', 'permissions', 'drive', 'board' ],
                'steps' => [
                    'verify_user_role',
                    'verify_drive_acl',
                    'verify_group_membership',
                    'verify_permission_inheritance',
                ],
            ],
            'lookup_profile' => [
                'key' => 'lookup_profile',
                'tool_key' => 'directory.context.lookup_profile',
                'version' => 1,
                'category' => 'context',
                'title' => 'Lookup Profile',
                'domain' => 'directory',
                'module' => 'people',
                'description' => 'Return a unified person, contact, or donor profile with directory and giving details.',
                'read_only' => true,
                'cache_ttl_seconds' => 60,
                'enclave_operation' => '',
                'idempotency_strategy' => 'request_hash',
                'diagnostic_tags' => [ 'directory', 'profile' ],
                'input_schema' => [
                    'type' => 'object',
                    'properties' => [
                        'profile_request' => [
                            'type' => 'object',
                            'required' => [ 'subject' ],
                            'properties' => [
                                'subject' => [ 'type' => 'string' ],
                                'entity_hint' => [ 'type' => 'string' ],
                            ],
                        ],
                    ],
                    'required' => [ 'profile_request' ],
                ],
                'output_schema' => [
                    'type' => 'object',
                    'required' => [ 'status', 'profile' ],
                ],
                'service' => [
                    'service' => 'hermes_directory',
                    'method' => 'lookupProfile',
                    'arguments_from_payload' => [ 'profile_request' ],
                ],
                'permission' => 'directory.lookup',
                'permission_requirements' => [
                    [
                        'type' => 'role_permission',
                        'permission_key' => 'directory.lookup',
                        'allowed_roles' => [ 'administrator', 'board', 'donor_admin', 'donor_user', 'newsletter_admin' ],
                    ],
                ],
                'context' => [ 'people', 'contacts', 'donations' ],
                'steps' => [ 'resolve_identity', 'load_related_records', 'return_profile_summary' ],
            ],
            'query_giving_summary' => [
                'key' => 'query_giving_summary',
                'tool_key' => 'donations.context.query_giving_summary',
                'version' => 1,
                'category' => 'context',
                'title' => 'Query Giving Summary',
                'domain' => 'donations',
                'module' => 'donations',
                'description' => 'Return aggregate giving totals for a requested period.',
                'read_only' => true,
                'cache_ttl_seconds' => 60,
                'enclave_operation' => '',
                'idempotency_strategy' => 'request_hash',
                'diagnostic_tags' => [ 'donations', 'reporting' ],
                'input_schema' => [
                    'type' => 'object',
                    'properties' => [
                        'giving_request' => [
                            'type' => 'object',
                            'properties' => [
                                'period' => [ 'type' => 'string' ],
                            ],
                        ],
                    ],
                    'required' => [],
                ],
                'output_schema' => [ 'type' => 'object', 'required' => [ 'status' ] ],
                'service' => [
                    'service' => 'hermes_directory',
                    'method' => 'queryGivingSummary',
                    'arguments_from_payload' => [ 'giving_request' ],
                ],
                'permission' => 'donations.view',
                'permission_requirements' => [
                    [
                        'type' => 'role_permission',
                        'permission_key' => 'donations.view',
                        'allowed_roles' => [ 'administrator', 'board', 'donor_admin', 'donor_user' ],
                    ],
                ],
                'context' => [ 'donations' ],
                'steps' => [ 'resolve_period', 'aggregate_gifts', 'return_summary' ],
            ],
            'query_capability_actors' => [
                'key' => 'query_capability_actors',
                'tool_key' => 'security.context.query_capability_actors',
                'version' => 1,
                'category' => 'context',
                'title' => 'Query Capability Actors',
                'domain' => 'security',
                'module' => 'people',
                'description' => 'List people who hold a specific effective capability, optionally filtered to board members.',
                'read_only' => true,
                'cache_ttl_seconds' => 60,
                'enclave_operation' => '',
                'idempotency_strategy' => 'request_hash',
                'diagnostic_tags' => [ 'security', 'capability' ],
                'input_schema' => [
                    'type' => 'object',
                    'properties' => [
                        'capability_request' => [
                            'type' => 'object',
                            'required' => [ 'permission_key' ],
                            'properties' => [
                                'permission_key' => [ 'type' => 'string' ],
                                'board_only' => [ 'type' => 'string' ],
                            ],
                        ],
                    ],
                    'required' => [ 'capability_request' ],
                ],
                'output_schema' => [
                    'type' => 'object',
                    'required' => [ 'status', 'actors' ],
                ],
                'service' => [
                    'service' => 'hermes_directory',
                    'method' => 'queryCapabilityActors',
                    'arguments_from_payload' => [ 'capability_request' ],
                ],
                'permission' => 'system.diagnostics.view',
                'permission_requirements' => [
                    [
                        'type' => 'role_permission',
                        'permission_key' => 'system.diagnostics.view',
                        'allowed_roles' => [ 'administrator', 'board', 'donor_admin' ],
                    ],
                ],
                'context' => [ 'people', 'permissions' ],
                'steps' => [ 'resolve_capability', 'load_matching_actors', 'return_capability_summary' ],
            ],
            'update_contact' => [
                'key' => 'update_contact',
                'tool_key' => 'contacts.action.update_contact',
                'version' => 1,
                'category' => 'action_proposal',
                'title' => 'Update Contact',
                'domain' => 'contacts',
                'module' => 'contacts',
                'description' => 'Update contact profile fields and newsletter list membership.',
                'read_only' => false,
                'cache_ttl_seconds' => 0,
                'enclave_operation' => 'hermes.command.update_contact',
                'idempotency_strategy' => 'subject_operation',
                'diagnostic_tags' => [ 'contacts', 'directory' ],
                'input_schema' => [
                    'type' => 'object',
                    'properties' => [
                        'contact_update_request' => [
                            'type' => 'object',
                            'required' => [ 'subject', 'operation' ],
                            'properties' => [
                                'subject' => [ 'type' => 'string' ],
                                'operation' => [ 'type' => 'string' ],
                                'field' => [ 'type' => 'string' ],
                                'value' => [ 'type' => 'string' ],
                                'list_name' => [ 'type' => 'string' ],
                            ],
                        ],
                    ],
                    'required' => [ 'contact_update_request' ],
                ],
                'output_schema' => [ 'type' => 'object', 'required' => [ 'status', 'message' ] ],
                'service' => [
                    'service' => 'hermes_contact_admin',
                    'method' => 'updateContact',
                    'arguments_from_payload' => [ 'contact_update_request' ],
                ],
                'permission' => 'contacts.edit',
                'permission_requirements' => [
                    [ 'type' => 'module_action', 'module' => 'contacts', 'action' => 'edit', 'permission_key' => 'contacts.edit' ],
                ],
                'context' => [ 'contacts', 'communications' ],
                'steps' => [ 'resolve_contact', 'apply_contact_update', 'confirm_updated_record' ],
            ],
            'create_user' => [
                'key' => 'create_user',
                'tool_key' => 'people.action.create_user',
                'version' => 1,
                'category' => 'action_proposal',
                'title' => 'Create User',
                'domain' => 'people',
                'module' => 'people',
                'description' => 'Create a new user/person record and optionally provision a Workspace account.',
                'read_only' => false,
                'cache_ttl_seconds' => 0,
                'enclave_operation' => 'hermes.command.create_user',
                'idempotency_strategy' => 'email',
                'diagnostic_tags' => [ 'people', 'onboarding' ],
                'input_schema' => [
                    'type' => 'object',
                    'properties' => [
                        'user_request' => [
                            'type' => 'object',
                            'required' => [ 'email' ],
                            'properties' => [
                                'email' => [ 'type' => 'string' ],
                                'first_name' => [ 'type' => 'string' ],
                                'last_name' => [ 'type' => 'string' ],
                                'display_name' => [ 'type' => 'string' ],
                                'password' => [ 'type' => 'string' ],
                            ],
                        ],
                    ],
                    'required' => [ 'user_request' ],
                ],
                'output_schema' => [ 'type' => 'object', 'required' => [ 'status', 'user' ] ],
                'service' => [
                    'service' => 'hermes_user_admin',
                    'method' => 'createUser',
                    'arguments_from_payload' => [ 'user_request' ],
                ],
                'permission' => 'people.create',
                'permission_requirements' => [
                    [ 'type' => 'module_action', 'module' => 'people', 'action' => 'create', 'permission_key' => 'people.create' ],
                ],
                'context' => [ 'people', 'permissions', 'drive' ],
                'steps' => [ 'validate_identity_inputs', 'create_person_record', 'assign_roles_and_workspace' ],
            ],
            'offboard_user' => [
                'key' => 'offboard_user',
                'tool_key' => 'people.action.offboard_user',
                'version' => 1,
                'category' => 'action_proposal',
                'title' => 'Offboard User',
                'domain' => 'people',
                'module' => 'people',
                'description' => 'Offboard a user and queue related Workspace suspension work.',
                'read_only' => false,
                'cache_ttl_seconds' => 0,
                'enclave_operation' => 'hermes.command.offboard_user',
                'idempotency_strategy' => 'subject',
                'diagnostic_tags' => [ 'people', 'offboarding' ],
                'input_schema' => [
                    'type' => 'object',
                    'properties' => [
                        'offboard_request' => [
                            'type' => 'object',
                            'required' => [ 'subject' ],
                            'properties' => [
                                'subject' => [ 'type' => 'string' ],
                            ],
                        ],
                    ],
                    'required' => [ 'offboard_request' ],
                ],
                'output_schema' => [ 'type' => 'object', 'required' => [ 'status', 'user' ] ],
                'service' => [
                    'service' => 'hermes_user_admin',
                    'method' => 'offboardUser',
                    'arguments_from_payload' => [ 'offboard_request' ],
                ],
                'permission' => 'people.edit',
                'permission_requirements' => [
                    [ 'type' => 'module_action', 'module' => 'people', 'action' => 'edit', 'permission_key' => 'people.edit' ],
                ],
                'context' => [ 'people', 'permissions', 'drive' ],
                'steps' => [ 'resolve_person', 'deactivate_local_access', 'queue_workspace_offboarding' ],
            ],
            'manage_user_roles' => [
                'key' => 'manage_user_roles',
                'tool_key' => 'people.action.manage_user_roles',
                'version' => 1,
                'category' => 'action_proposal',
                'title' => 'Manage User Roles',
                'domain' => 'people',
                'module' => 'people',
                'description' => 'Assign, remove, or replace Metis roles for a person.',
                'read_only' => false,
                'cache_ttl_seconds' => 0,
                'enclave_operation' => 'hermes.command.manage_user_roles',
                'idempotency_strategy' => 'subject_roles',
                'diagnostic_tags' => [ 'people', 'roles' ],
                'input_schema' => [
                    'type' => 'object',
                    'properties' => [
                        'role_request' => [
                            'type' => 'object',
                            'required' => [ 'subject' ],
                            'properties' => [
                                'subject' => [ 'type' => 'string' ],
                                'mode' => [ 'type' => 'string' ],
                            ],
                        ],
                    ],
                    'required' => [ 'role_request' ],
                ],
                'output_schema' => [ 'type' => 'object', 'required' => [ 'status', 'user' ] ],
                'service' => [
                    'service' => 'hermes_user_admin',
                    'method' => 'manageUserRoles',
                    'arguments_from_payload' => [ 'role_request' ],
                ],
                'permission' => 'people.edit',
                'permission_requirements' => [
                    [ 'type' => 'module_action', 'module' => 'people', 'action' => 'edit', 'permission_key' => 'people.edit' ],
                ],
                'context' => [ 'people', 'permissions' ],
                'steps' => [ 'resolve_person', 'validate_roles', 'apply_role_changes' ],
            ],
            'manage_workspace_groups' => [
                'key' => 'manage_workspace_groups',
                'tool_key' => 'people.action.manage_workspace_groups',
                'version' => 1,
                'category' => 'action_proposal',
                'title' => 'Manage Workspace Groups',
                'domain' => 'people',
                'module' => 'people',
                'description' => 'Add or remove a Workspace user from one or more groups.',
                'read_only' => false,
                'cache_ttl_seconds' => 0,
                'enclave_operation' => 'hermes.command.manage_workspace_groups',
                'idempotency_strategy' => 'subject_groups',
                'diagnostic_tags' => [ 'people', 'workspace' ],
                'input_schema' => [
                    'type' => 'object',
                    'properties' => [
                        'group_request' => [
                            'type' => 'object',
                            'required' => [ 'subject' ],
                            'properties' => [
                                'subject' => [ 'type' => 'string' ],
                                'mode' => [ 'type' => 'string' ],
                            ],
                        ],
                    ],
                    'required' => [ 'group_request' ],
                ],
                'output_schema' => [ 'type' => 'object', 'required' => [ 'status', 'user' ] ],
                'service' => [
                    'service' => 'hermes_user_admin',
                    'method' => 'manageWorkspaceGroups',
                    'arguments_from_payload' => [ 'group_request' ],
                ],
                'permission' => 'people.workspace_manage',
                'permission_requirements' => [
                    [ 'type' => 'module_action', 'module' => 'people', 'action' => 'workspace_manage', 'permission_key' => 'people.workspace_manage' ],
                ],
                'context' => [ 'people', 'drive' ],
                'steps' => [ 'resolve_workspace_user', 'validate_group_targets', 'apply_group_membership_changes' ],
            ],
            'reset_workspace_password' => [
                'key' => 'reset_workspace_password',
                'tool_key' => 'people.action.reset_workspace_password',
                'version' => 1,
                'category' => 'action_proposal',
                'title' => 'Reset Workspace Password',
                'domain' => 'people',
                'module' => 'people',
                'description' => 'Set a new Workspace password for a user and return the credential package.',
                'read_only' => false,
                'cache_ttl_seconds' => 0,
                'enclave_operation' => 'hermes.command.reset_workspace_password',
                'idempotency_strategy' => 'subject_password',
                'diagnostic_tags' => [ 'people', 'workspace', 'security' ],
                'input_schema' => [
                    'type' => 'object',
                    'properties' => [
                        'password_request' => [
                            'type' => 'object',
                            'required' => [ 'subject' ],
                            'properties' => [
                                'subject' => [ 'type' => 'string' ],
                                'new_password' => [ 'type' => 'string' ],
                            ],
                        ],
                    ],
                    'required' => [ 'password_request' ],
                ],
                'output_schema' => [ 'type' => 'object', 'required' => [ 'status', 'user' ] ],
                'service' => [
                    'service' => 'hermes_user_admin',
                    'method' => 'resetWorkspacePassword',
                    'arguments_from_payload' => [ 'password_request' ],
                ],
                'permission' => 'people.workspace_manage',
                'permission_requirements' => [
                    [ 'type' => 'module_action', 'module' => 'people', 'action' => 'workspace_manage', 'permission_key' => 'people.workspace_manage' ],
                ],
                'context' => [ 'people' ],
                'steps' => [ 'resolve_workspace_user', 'set_new_password', 'return_credential_package' ],
            ],
            'reset_metis_password' => [
                'key' => 'reset_metis_password',
                'tool_key' => 'people.action.reset_metis_password',
                'version' => 1,
                'category' => 'action_proposal',
                'title' => 'Reset Metis Password',
                'domain' => 'people',
                'module' => 'people',
                'description' => 'Set a new Metis password for a user and return the credential package.',
                'read_only' => false,
                'cache_ttl_seconds' => 0,
                'enclave_operation' => 'hermes.command.reset_metis_password',
                'idempotency_strategy' => 'subject_password',
                'diagnostic_tags' => [ 'people', 'security' ],
                'input_schema' => [
                    'type' => 'object',
                    'properties' => [
                        'password_request' => [
                            'type' => 'object',
                            'required' => [ 'subject' ],
                            'properties' => [
                                'subject' => [ 'type' => 'string' ],
                                'new_password' => [ 'type' => 'string' ],
                            ],
                        ],
                    ],
                    'required' => [ 'password_request' ],
                ],
                'output_schema' => [ 'type' => 'object', 'required' => [ 'status', 'user' ] ],
                'service' => [
                    'service' => 'hermes_user_admin',
                    'method' => 'resetMetisPassword',
                    'arguments_from_payload' => [ 'password_request' ],
                ],
                'permission' => 'people.edit',
                'permission_requirements' => [
                    [ 'type' => 'module_action', 'module' => 'people', 'action' => 'edit', 'permission_key' => 'people.edit' ],
                ],
                'context' => [ 'people' ],
                'steps' => [ 'resolve_person', 'set_new_metis_password', 'return_credential_package' ],
            ],
            'reset_user_mfa' => [
                'key' => 'reset_user_mfa',
                'tool_key' => 'people.action.reset_user_mfa',
                'version' => 1,
                'category' => 'action_proposal',
                'title' => 'Reset User MFA',
                'domain' => 'people',
                'module' => 'people',
                'description' => 'Reset MFA state, clear TOTP secret, and revoke active passkeys.',
                'read_only' => false,
                'cache_ttl_seconds' => 0,
                'enclave_operation' => 'hermes.command.reset_user_mfa',
                'idempotency_strategy' => 'subject',
                'diagnostic_tags' => [ 'people', 'security', 'mfa' ],
                'input_schema' => [
                    'type' => 'object',
                    'properties' => [
                        'mfa_request' => [
                            'type' => 'object',
                            'required' => [ 'subject' ],
                            'properties' => [
                                'subject' => [ 'type' => 'string' ],
                            ],
                        ],
                    ],
                    'required' => [ 'mfa_request' ],
                ],
                'output_schema' => [ 'type' => 'object', 'required' => [ 'status', 'user' ] ],
                'service' => [
                    'service' => 'hermes_user_admin',
                    'method' => 'resetUserMfa',
                    'arguments_from_payload' => [ 'mfa_request' ],
                ],
                'permission' => 'people.edit',
                'permission_requirements' => [
                    [ 'type' => 'module_action', 'module' => 'people', 'action' => 'edit', 'permission_key' => 'people.edit' ],
                ],
                'context' => [ 'people', 'security' ],
                'steps' => [ 'resolve_person', 'revoke_mfa_artifacts', 'confirm_mfa_reset' ],
            ],
            'clarify_password_reset' => [
                'key' => 'clarify_password_reset',
                'tool_key' => 'people.context.clarify_password_reset',
                'version' => 1,
                'category' => 'context',
                'title' => 'Clarify Password Reset',
                'domain' => 'people',
                'module' => 'people',
                'description' => 'Ask whether to reset the Metis password or Workspace password.',
                'read_only' => true,
                'cache_ttl_seconds' => 0,
                'enclave_operation' => '',
                'idempotency_strategy' => 'request_hash',
                'diagnostic_tags' => [ 'people' ],
                'input_schema' => [
                    'type' => 'object',
                    'properties' => [
                        'password_request' => [
                            'type' => 'object',
                            'required' => [ 'subject' ],
                            'properties' => [
                                'subject' => [ 'type' => 'string' ],
                            ],
                        ],
                    ],
                    'required' => [ 'password_request' ],
                ],
                'output_schema' => [ 'type' => 'object', 'required' => [ 'status', 'message' ] ],
                'service' => [
                    'service' => 'hermes_user_admin',
                    'method' => 'clarifyPasswordReset',
                    'arguments_from_payload' => [ 'password_request' ],
                ],
                'permission' => 'people.edit',
                'permission_requirements' => [
                    [ 'type' => 'module_action', 'module' => 'people', 'action' => 'edit', 'permission_key' => 'people.edit' ],
                ],
                'context' => [ 'people' ],
                'steps' => [ 'resolve_person', 'ask_reset_target' ],
            ],
            'link_drive_folder' => [
                'key' => 'link_drive_folder',
                'tool_key' => 'drive.action.link_drive_folder',
                'version' => 1,
                'category' => 'action_proposal',
                'title' => 'Link Drive Folder',
                'domain' => 'drive',
                'module' => 'drive',
                'description' => 'Create or link a Drive folder for a person record.',
                'read_only' => false,
                'cache_ttl_seconds' => 0,
                'enclave_operation' => 'hermes.command.link_drive_folder',
                'idempotency_strategy' => 'subject_folder',
                'diagnostic_tags' => [ 'drive', 'people' ],
                'input_schema' => [
                    'type' => 'object',
                    'properties' => [
                        'drive_request' => [
                            'type' => 'object',
                            'required' => [ 'subject' ],
                            'properties' => [
                                'subject' => [ 'type' => 'string' ],
                                'folder_id' => [ 'type' => 'string' ],
                            ],
                        ],
                    ],
                    'required' => [ 'drive_request' ],
                ],
                'output_schema' => [ 'type' => 'object', 'required' => [ 'status', 'folder' ] ],
                'service' => [
                    'service' => 'hermes_user_admin',
                    'method' => 'linkDriveFolder',
                    'arguments_from_payload' => [ 'drive_request' ],
                ],
                'permission' => 'people.edit',
                'permission_requirements' => [
                    [ 'type' => 'module_action', 'module' => 'people', 'action' => 'edit', 'permission_key' => 'people.edit' ],
                ],
                'context' => [ 'people', 'drive' ],
                'steps' => [ 'resolve_person', 'validate_drive_target', 'link_folder_mapping' ],
            ],
            'create_post' => [
                'key' => 'create_post',
                'tool_key' => 'website.action.create_post',
                'version' => 1,
                'category' => 'action_proposal',
                'title' => 'Create Post',
                'domain' => 'website',
                'module' => 'website',
                'description' => 'Create a website post draft from a requested title.',
                'read_only' => false,
                'cache_ttl_seconds' => 0,
                'enclave_operation' => 'hermes.command.create_post',
                'idempotency_strategy' => 'title',
                'diagnostic_tags' => [ 'website', 'content' ],
                'input_schema' => [
                    'type' => 'object',
                    'properties' => [
                        'post_request' => [
                            'type' => 'object',
                            'required' => [ 'title' ],
                            'properties' => [
                                'title' => [ 'type' => 'string' ],
                                'slug' => [ 'type' => 'string' ],
                                'excerpt' => [ 'type' => 'string' ],
                                'status' => [ 'type' => 'string' ],
                            ],
                        ],
                    ],
                    'required' => [ 'post_request' ],
                ],
                'output_schema' => [ 'type' => 'object', 'required' => [ 'status', 'post' ] ],
                'service' => [
                    'service' => 'hermes_website_admin',
                    'method' => 'createPost',
                    'arguments_from_payload' => [ 'post_request' ],
                ],
                'permission' => 'website.edit',
                'permission_requirements' => [
                    [ 'type' => 'module_action', 'module' => 'website', 'action' => 'edit', 'permission_key' => 'website.edit' ],
                ],
                'context' => [ 'cms_content' ],
                'steps' => [ 'validate_post_request', 'create_post_draft', 'confirm_post_record' ],
            ],
            'publish_post' => [
                'key' => 'publish_post',
                'tool_key' => 'website.action.publish_post',
                'version' => 1,
                'category' => 'action_proposal',
                'title' => 'Publish Post',
                'domain' => 'website',
                'module' => 'website',
                'description' => 'Publish an existing website post by title, slug, or code.',
                'read_only' => false,
                'cache_ttl_seconds' => 0,
                'enclave_operation' => 'hermes.command.publish_post',
                'idempotency_strategy' => 'subject',
                'diagnostic_tags' => [ 'website', 'content' ],
                'input_schema' => [
                    'type' => 'object',
                    'properties' => [
                        'post_request' => [
                            'type' => 'object',
                            'required' => [ 'subject' ],
                            'properties' => [
                                'subject' => [ 'type' => 'string' ],
                            ],
                        ],
                    ],
                    'required' => [ 'post_request' ],
                ],
                'output_schema' => [ 'type' => 'object', 'required' => [ 'status', 'post' ] ],
                'service' => [
                    'service' => 'hermes_website_admin',
                    'method' => 'publishPost',
                    'arguments_from_payload' => [ 'post_request' ],
                ],
                'permission' => 'website.edit',
                'permission_requirements' => [
                    [ 'type' => 'module_action', 'module' => 'website', 'action' => 'edit', 'permission_key' => 'website.edit' ],
                ],
                'context' => [ 'cms_content' ],
                'steps' => [ 'resolve_post', 'publish_post', 'confirm_publish_state' ],
            ],
            'aut_update_check' => [
                'key' => 'aut_update_check',
                'tool_key' => 'system.action.aut_update_check',
                'version' => 1,
                'category' => 'diagnostic',
                'title' => 'Check for Updates',
                'domain' => 'system',
                'module' => 'settings',
                'description' => 'Check GitHub release metadata and compare it with the installed Metis version.',
                'read_only' => true,
                'cache_ttl_seconds' => 300,
                'enclave_operation' => '',
                'idempotency_strategy' => 'request_hash',
                'diagnostic_tags' => [ 'system', 'update' ],
                'input_schema' => [
                    'type' => 'object',
                    'properties' => [],
                    'required' => [],
                ],
                'output_schema' => [ 'type' => 'object', 'required' => [ 'current_version', 'latest_version', 'update_available' ] ],
                'service' => [
                    'service' => 'github_update',
                    'method' => 'checkForUpdates',
                    'arguments' => [ false ],
                ],
                'permission' => 'system.diagnostics.view',
                'permission_requirements' => [
                    [ 'type' => 'role_permission', 'permission_key' => 'system.diagnostics.view', 'allowed_roles' => [ 'administrator', 'board' ] ],
                ],
                'context' => [ 'system' ],
                'steps' => [ 'read_current_version', 'query_github_release', 'compare_versions' ],
            ],
            'aut_update_install' => [
                'key' => 'aut_update_install',
                'tool_key' => 'system.action.aut_update_install',
                'version' => 1,
                'category' => 'action_proposal',
                'title' => 'Install Update',
                'domain' => 'system',
                'module' => 'settings',
                'description' => 'Install the latest approved release through the core update service.',
                'read_only' => false,
                'cache_ttl_seconds' => 0,
                'enclave_operation' => 'hermes.command.aut_update_install',
                'idempotency_strategy' => 'latest_release',
                'diagnostic_tags' => [ 'system', 'update' ],
                'input_schema' => [
                    'type' => 'object',
                    'properties' => [],
                    'required' => [],
                ],
                'output_schema' => [ 'type' => 'object', 'required' => [ 'status' ] ],
                'service' => [
                    'service' => 'updates',
                    'method' => 'installUpdate',
                    'arguments' => [ null, 'hermes' ],
                ],
                'permission' => 'system.backup.execute',
                'permission_requirements' => [
                    [ 'type' => 'role_permission', 'permission_key' => 'system.backup.execute', 'allowed_roles' => [ 'administrator', 'board' ] ],
                ],
                'context' => [ 'system' ],
                'steps' => [ 'download_release_archive', 'verify_integrity', 'install_release', 'reload_runtime' ],
            ],
            'aut_self_heal' => [
                'key' => 'aut_self_heal',
                'tool_key' => 'system.action.aut_self_heal',
                'version' => 1,
                'category' => 'action_proposal',
                'title' => 'Run Self-Heal',
                'domain' => 'system',
                'module' => 'settings',
                'description' => 'Run file integrity validation, repair caches, and restore damaged assets when possible.',
                'read_only' => false,
                'cache_ttl_seconds' => 0,
                'enclave_operation' => 'hermes.command.aut_self_heal',
                'idempotency_strategy' => 'manual_trigger',
                'diagnostic_tags' => [ 'system', 'integrity', 'repair' ],
                'input_schema' => [
                    'type' => 'object',
                    'properties' => [],
                    'required' => [],
                ],
                'output_schema' => [ 'type' => 'object', 'required' => [ 'status' ] ],
                'service' => [
                    'service' => 'self_healing',
                    'method' => 'repairSystem',
                    'arguments' => [ 'hermes' ],
                ],
                'permission' => 'system.backup.execute',
                'permission_requirements' => [
                    [ 'type' => 'role_permission', 'permission_key' => 'system.backup.execute', 'allowed_roles' => [ 'administrator', 'board' ] ],
                ],
                'context' => [ 'system' ],
                'steps' => [ 'run_integrity_scan', 'restore_changed_files', 'rebuild_caches', 'repair_configuration' ],
            ],
        ];
    }

    public function definition( string $command ): ?array {
        return $this->definitions()[ \metis_key_clean( $command ) ] ?? null;
    }
}
