<?php
return [
    'allow_git_recovery' => true,
    'automatic_file_recovery_enabled' => true,
    'recovery_preboot_enabled' => true,
    'recovery_runtime_enabled' => true,
    'recovery_file_mutation_enabled' => true,
    'allowed_git_remotes' => [
        'https://github.com/jvitarius85/metis.git',
        'git@github.com:jvitarius85/metis.git',
    ],
    'allowed_fallback_branch' => 'stable',
    'require_signed_tags' => false,
    'allow_latest_fallback' => false,
    'max_recovery_attempts' => 2,
    'backup_required_before_git_restore' => true,
    'maintenance_mode_on_failure' => true,
    'lock_ttl_seconds' => 900,
    'backup_root' => '/Volumes/NAS/backups 2',
    'critical_files' => [
        'index.php',
        'system/shell.php',
        'system/vendor/autoload.php',
        'system/src/Metis/Core/Runtime/StandaloneApplicationBootstrap.php',
        'system/src/Metis/Core/Routing/RouterRuntime.php',
        'system/src/Metis/Core/Security/SecurityEnclave.php',
        'system/src/Metis/Core/Security/SecurityRuntimeBridge.php',
        'system/src/Metis/Core/ModuleLoader.php',
        'system/src/Metis/Core/Recovery/PrebootIntegrityService.php',
        'system/src/Metis/Core/Recovery/RecoveryPolicyService.php',
        'system/src/Metis/Core/Recovery/RecoveryVerifier.php',
        'system/src/Metis/Core/Recovery/BackupRecoveryService.php',
        'system/src/Metis/Core/Recovery/GitRecoveryService.php',
    ],
    'preserve_paths' => [
        '.env',
        'config.php',
        'database.php',
        'system/config/database.php',
        'system/config/auth',
        'storage',
        'uploads',
        'logs',
        'cache',
        'grandys_stash',
    ],
];
